// ─────────────────────────────────────────────────────────────
// Trip content. This is the only file that holds your plans.
// ─────────────────────────────────────────────────────────────

const TRIP = {
  title: "Paris",
  start: "2026-10-28",
  end: "2026-11-02",    // departure day
  arrival:   { time: "11:43", where: "Gare du Nord" },
  departure: { time: "18:15", where: "Gare du Nord" },
  stay: null,           // hotel being booked: { name: "", address: "", phone: "", lat: 0, lng: 0 }
};

// cat: "eat" | "drink" | "cafe" | "pastry" | "shop" | "go" | "do"
// status: "want" | "maybe" | "skip"
// open: "HH:MM-HH:MM" every day · openOn: per-day hours · closed: days it's shut
// tags drive the filters and lists: "view", "instagram", "neighbourhood", "rainy", "free", "to book", …
const PLACES = [

  // ── Eat ──
  {
    id: "chartier-grands-boulevards",
    name: "Bouillon Chartier · Grands Boulevards",
    cat: "eat",
    area: "Grands Boulevards",
    address: "7 Rue du Faubourg Montmartre, 75009 Paris",
    lat: 48.87194,
    lng: 2.34301,
    order: ["Escargots", "Steak frites", "Boeuf bourguignon", "Chocolate mousse"],
    notes: "The original 1896 dining hall. Classic French dishes at low prices. No reservations, so expect a queue at peak times.",
    hours: "Every day 11:30 – midnight",
    open: "11:30-24:00",
    status: "want",
    tags: ["french classics", "cheap", "instagram", "bouillon"],
  },
  {
    id: "chartier-montparnasse",
    name: "Bouillon Chartier · Montparnasse",
    cat: "eat",
    area: "Montparnasse",
    address: "59 Boulevard du Montparnasse, 75006 Paris",
    lat: 48.84432,
    lng: 2.32327,
    order: ["Escargots", "Steak frites", "Boeuf bourguignon", "Chocolate mousse"],
    notes: "Art Nouveau dining room. No reservations, so expect a queue at peak times.",
    hours: "Every day 11:30 – midnight",
    open: "11:30-24:00",
    status: "want",
    tags: ["french classics", "cheap", "instagram", "bouillon"],
  },
  {
    id: "chartier-gare-de-lest",
    name: "Bouillon Chartier · Gare de l'Est",
    cat: "eat",
    area: "Canal Saint-Martin",
    address: "5 Rue du 8 Mai 1945, 75010 Paris",
    lat: 48.87597,
    lng: 2.35873,
    order: ["Escargots", "Steak frites", "Boeuf bourguignon", "Chocolate mousse"],
    notes: "Opposite Gare de l'Est. No reservations.",
    status: "want",
    tags: ["french classics", "cheap", "bouillon"],
  },
  {
    id: "les-philosophes",
    name: "Les Philosophes",
    cat: "eat",
    area: "Le Marais",
    address: "28 Rue Vieille du Temple, 75004 Paris",
    lat: 48.85731,
    lng: 2.35752,
    order: ["French onion soup"],
    notes: "Marais bistro with a busy terrace. The French onion soup is the favourite.",
    status: "want",
    tags: ["french classics", "terrace"],
  },
  {
    id: "bistrot-paul-bert",
    name: "Bistrot Paul Bert",
    cat: "eat",
    area: "Bastille & 11th",
    address: "18 Rue Paul Bert, 75011 Paris",
    lat: 48.85223,
    lng: 2.38487,
    order: ["Steak au poivre with frites"],
    notes: "One of the most loved classic bistros in Paris. Book a table.",
    status: "want",
    tags: ["french classics"],
  },
  {
    id: "fontaine-de-mars",
    name: "La Fontaine de Mars",
    cat: "eat",
    area: "Eiffel Tower & Trocadéro",
    address: "129 Rue Saint-Dominique, 75007 Paris",
    lat: 48.85845,
    lng: 2.30252,
    order: ["Duck confit", "Escargots"],
    notes: "Classic red-checked bistro a few minutes from the Eiffel Tower. Good to book.",
    status: "want",
    tags: ["french classics"],
  },
  {
    id: "relais-entrecote",
    name: "Le Relais de l'Entrecôte",
    cat: "eat",
    area: "Saint-Germain",
    address: "20 Rue Saint-Benoît, 75006 Paris",
    lat: 48.85465,
    lng: 2.33283,
    order: ["Steak frites with the house sauce"],
    notes: "Only one menu: salad, then steak frites with the secret house sauce, and a second serving. No reservations, so expect a queue.",
    status: "want",
    tags: ["french classics"],
  },
  {
    id: "au-pied-de-cochon",
    name: "Au Pied de Cochon",
    cat: "eat",
    area: "Montorgueil & Les Halles",
    address: "6 Rue Coquillière, 75001 Paris",
    lat: 48.86349,
    lng: 2.34372,
    order: ["French onion soup"],
    notes: "Classic brasserie near Les Halles, open late.",
    status: "want",
    tags: ["french classics", "late night"],
  },
  {
    id: "bouillon-julien",
    name: "Bouillon Julien",
    cat: "eat",
    area: "Grands Boulevards",
    address: "16 Rue du Faubourg Saint-Denis, 75010 Paris",
    lat: 48.87055,
    lng: 2.35318,
    order: ["Escargots", "Steak frites"],
    notes: "Stunning Art Nouveau dining room with bouillon prices.",
    status: "want",
    tags: ["french classics", "cheap", "instagram"],
  },
  {
    id: "bouillon-pigalle",
    name: "Bouillon Pigalle",
    cat: "eat",
    area: "Pigalle & Rue des Martyrs",
    address: "22 Boulevard de Clichy, 75018 Paris",
    lat: 48.88262,
    lng: 2.33741,
    order: ["Boeuf bourguignon"],
    notes: "Big, lively and cheap French classics near Pigalle.",
    status: "want",
    tags: ["french classics", "cheap"],
  },
  {
    id: "train-bleu",
    name: "Le Train Bleu",
    cat: "eat",
    area: "Bastille & Gare de Lyon",
    address: "Place Louis-Armand, Gare de Lyon, 75012 Paris",
    lat: 48.8447,
    lng: 2.3734,
    notes: "Belle Époque restaurant inside Gare de Lyon, with gilded painted ceilings. Worth it for the room. Book ahead.",
    status: "want",
    tags: ["french classics", "instagram"],
  },
  {
    id: "breizh-cafe",
    name: "Breizh Café",
    cat: "eat",
    area: "Le Marais",
    address: "109 Rue Vieille du Temple, 75003 Paris",
    lat: 48.86062,
    lng: 2.36186,
    order: ["Buckwheat galette", "Salted butter caramel crêpe"],
    drinks: ["Breton cider"],
    notes: "The best-known crêperie in Paris.",
    status: "want",
    tags: ["crêpes"],
  },
  {
    id: "as-du-fallafel",
    name: "L'As du Fallafel",
    cat: "eat",
    area: "Le Marais",
    address: "34 Rue des Rosiers, 75004 Paris",
    lat: 48.85741,
    lng: 2.35905,
    order: ["Falafel pita"],
    notes: "Famous falafel pita in the old Jewish quarter. Takeaway window or seats inside.",
    hours: "Closed Friday evening and Saturday",
    closed: ["sat"],
    status: "want",
    tags: ["cheap"],
  },
  {
    id: "pink-mamma",
    name: "Pink Mamma",
    cat: "eat",
    area: "Pigalle & Rue des Martyrs",
    address: "20 bis Rue de Douai, 75009 Paris",
    lat: 48.8819,
    lng: 2.33456,
    order: ["Truffle pasta"],
    notes: "Italian restaurant over four floors with a plant-filled glass-roofed top floor. Very Instagrammable.",
    status: "want",
    tags: ["instagram"],
  },
  {
    id: "higuma",
    name: "Higuma",
    cat: "eat",
    area: "Little Tokyo",
    address: "32 bis Rue Sainte-Anne, 75001 Paris",
    lat: 48.86661,
    lng: 2.33575,
    order: ["Ramen", "Gyoza"],
    notes: "Busy, cheap ramen counter. A Rue Sainte-Anne classic.",
    status: "want",
    tags: ["japanese", "cheap"],
  },
  {
    id: "kunitoraya",
    name: "Kunitoraya",
    cat: "eat",
    area: "Little Tokyo",
    address: "5 Rue Villedo, 75001 Paris",
    lat: 48.86618,
    lng: 2.33634,
    order: ["Udon"],
    notes: "Handmade udon. There's almost always a queue.",
    status: "want",
    tags: ["japanese"],
  },
  {
    id: "sanukiya",
    name: "Sanukiya",
    cat: "eat",
    area: "Little Tokyo",
    address: "9 Rue d'Argenteuil, 75001 Paris",
    lat: 48.86469,
    lng: 2.3338,
    order: ["Udon"],
    notes: "Hand-pulled udon, hot or cold. Long lines at peak hours.",
    status: "want",
    tags: ["japanese", "cheap"],
  },
  {
    id: "dosanko-larmen",
    name: "Dosanko Larmen",
    cat: "eat",
    area: "Little Tokyo",
    address: "40 Rue Sainte-Anne, 75002 Paris",
    lat: 48.86707,
    lng: 2.33598,
    order: ["Ramen", "Gyoza"],
    notes: "Small place with huge ramen bowls and great gyoza.",
    status: "want",
    tags: ["japanese", "cheap"],
  },
  {
    id: "pho-14",
    name: "Pho 14",
    cat: "eat",
    area: "Chinatown",
    address: "129 Avenue de Choisy, 75013 Paris",
    lat: 48.82641,
    lng: 2.35953,
    order: ["Pho"],
    notes: "Popular Vietnamese pho in Chinatown. Quick and cheap.",
    status: "want",
    tags: ["asian", "cheap"],
  },
  {
    id: "dong-huong",
    name: "Dong Huong",
    cat: "eat",
    area: "Belleville",
    address: "14 Rue Louis Bonnet, 75011 Paris",
    lat: 48.87123,
    lng: 2.37685,
    order: ["Pho", "Bò bún"],
    notes: "Long-running Vietnamese restaurant in Belleville.",
    status: "want",
    tags: ["asian", "cheap"],
  },

  // ── Drink ──
  {
    id: "little-red-door",
    name: "Little Red Door",
    cat: "drink",
    area: "Le Marais",
    address: "60 Rue Charlot, 75003 Paris",
    lat: 48.86366,
    lng: 2.36359,
    notes: "Regularly listed among the world's best cocktail bars. Look for the small red door. Arrive early or expect a wait.",
    status: "want",
    tags: ["cocktails"],
  },
  {
    id: "le-syndicat",
    name: "Le Syndicat",
    cat: "drink",
    area: "Grands Boulevards",
    address: "51 Rue du Faubourg Saint-Denis, 75010 Paris",
    lat: 48.87179,
    lng: 2.35366,
    notes: "Cocktails made only with French spirits, behind a poster-covered front.",
    status: "want",
    tags: ["cocktails"],
  },
  {
    id: "candelaria",
    name: "Candelaria",
    cat: "drink",
    area: "Le Marais",
    address: "52 Rue de Saintonge, 75003 Paris",
    lat: 48.86299,
    lng: 2.36402,
    notes: "Hidden cocktail bar through a door at the back of a small taqueria.",
    status: "want",
    tags: ["cocktails"],
  },
  {
    id: "danico",
    name: "Danico",
    cat: "drink",
    area: "Louvre & Tuileries",
    address: "6 Rue Vivienne, 75002 Paris",
    lat: 48.86712,
    lng: 2.33929,
    notes: "Cocktail bar at the back of the Daroco restaurant, next to Galerie Vivienne.",
    status: "want",
    tags: ["cocktails"],
  },
  {
    id: "bar-hemingway",
    name: "Bar Hemingway",
    cat: "drink",
    area: "Opéra",
    address: "15 Place Vendôme, 75001 Paris",
    lat: 48.86795,
    lng: 2.3289,
    notes: "Small wood-panelled bar inside the Ritz. Classic and expensive. Dress smart.",
    status: "want",
    tags: ["cocktails", "classic"],
  },
  {
    id: "harrys-bar",
    name: "Harry's New York Bar",
    cat: "drink",
    area: "Opéra",
    address: "5 Rue Daunou, 75002 Paris",
    lat: 48.86925,
    lng: 2.33213,
    drinks: ["Bloody Mary"],
    notes: "Historic bar where the Bloody Mary is said to have been invented.",
    status: "want",
    tags: ["cocktails", "classic"],
  },
  {
    id: "le-perchoir",
    name: "Le Perchoir Ménilmontant",
    cat: "drink",
    area: "Belleville",
    address: "14 Rue Crespin du Gast, 75011 Paris",
    lat: 48.86539,
    lng: 2.382,
    notes: "The rooftop bar that started the Paris trend, with views towards Sacré-Cœur. Rooftops can close in bad weather, so check before going.",
    bestTime: "Sunset",
    status: "want",
    tags: ["rooftop", "view", "cocktails", "instagram"],
  },
  {
    id: "les-ombres",
    name: "Les Ombres",
    cat: "drink",
    area: "Eiffel Tower & Trocadéro",
    address: "27 Quai Branly, 75007 Paris",
    lat: 48.86179,
    lng: 2.29868,
    notes: "Rooftop restaurant and bar on the Musée du quai Branly, directly facing the Eiffel Tower. Book for dinner.",
    bestTime: "After dark, when the tower sparkles on the hour",
    status: "want",
    tags: ["rooftop", "view", "instagram"],
  },
  {
    id: "terrass-hotel",
    name: "Terrass'' Hôtel rooftop",
    cat: "drink",
    area: "Montmartre",
    address: "12 Rue Joseph de Maistre, 75018 Paris",
    lat: 48.88647,
    lng: 2.33313,
    notes: "Rooftop bar on top of a Montmartre hotel with a view over Paris to the Eiffel Tower.",
    bestTime: "Sunset",
    status: "want",
    tags: ["rooftop", "view", "cocktails"],
  },
  {
    id: "baron-rouge",
    name: "Le Baron Rouge",
    cat: "drink",
    area: "Bastille & Gare de Lyon",
    address: "1 Rue Théophile Roussel, 75012 Paris",
    lat: 48.84944,
    lng: 2.37744,
    notes: "Lively, old-school wine bar by the Marché d'Aligre. Wine straight from the barrel.",
    status: "want",
    tags: ["wine", "cheap"],
  },
  {
    id: "frenchie-bar-a-vins",
    name: "Frenchie Bar à Vins",
    cat: "drink",
    area: "Montorgueil & Les Halles",
    address: "6 Rue du Nil, 75002 Paris",
    lat: 48.86781,
    lng: 2.34795,
    notes: "Wine bar with excellent small plates. No reservations, so go early.",
    status: "want",
    tags: ["wine"],
  },

  // ── Cafés ──
  {
    id: "cafe-de-flore",
    name: "Café de Flore",
    cat: "cafe",
    area: "Saint-Germain",
    address: "172 Boulevard Saint-Germain, 75006 Paris",
    lat: 48.85413,
    lng: 2.33255,
    drinks: ["Hot chocolate", "Café crème"],
    notes: "Classic Paris café since the 1880s. The photo is under the white awning outside.",
    status: "want",
    tags: ["classic", "instagram", "terrace", "hot chocolate"],
  },
  {
    id: "deux-magots",
    name: "Les Deux Magots",
    cat: "cafe",
    area: "Saint-Germain",
    address: "6 Place Saint-Germain-des-Prés, 75006 Paris",
    lat: 48.85407,
    lng: 2.33306,
    drinks: ["Hot chocolate"],
    notes: "Famous literary café next door to Café de Flore. Terrace facing the church.",
    status: "want",
    tags: ["classic", "terrace", "hot chocolate"],
  },
  {
    id: "maison-rose",
    name: "La Maison Rose",
    cat: "cafe",
    area: "Montmartre",
    address: "2 Rue de l'Abreuvoir, 75018 Paris",
    lat: 48.88797,
    lng: 2.33961,
    notes: "The pink house. The most photographed café front in Paris.",
    bestTime: "Before 9:00, for the photo without crowds",
    status: "want",
    tags: ["instagram"],
  },
  {
    id: "le-consulat",
    name: "Le Consulat",
    cat: "cafe",
    area: "Montmartre",
    address: "18 Rue Norvins, 75018 Paris",
    lat: 48.887,
    lng: 2.34,
    notes: "Picture-postcard corner café near Place du Tertre.",
    status: "want",
    tags: ["instagram", "classic", "terrace"],
  },
  {
    id: "deux-moulins",
    name: "Café des Deux Moulins",
    cat: "cafe",
    area: "Montmartre",
    address: "15 Rue Lepic, 75018 Paris",
    lat: 48.8849,
    lng: 2.3337,
    order: ["Crème brûlée"],
    notes: "The café from the film Amélie.",
    status: "want",
    tags: ["film"],
  },
  {
    id: "angelina",
    name: "Angelina Rivoli",
    cat: "cafe",
    area: "Louvre & Tuileries",
    address: "226 Rue de Rivoli, 75001 Paris",
    lat: 48.86508,
    lng: 2.32841,
    order: ["Mont-Blanc"],
    drinks: ["L'Africain hot chocolate"],
    notes: "Belle Époque tea room. Famous for thick hot chocolate and the Mont-Blanc. Expect a queue.",
    status: "want",
    tags: ["hot chocolate", "pastry", "instagram", "rainy"],
  },
  {
    id: "kitsune-palais-royal",
    name: "Café Kitsuné Palais Royal",
    cat: "cafe",
    area: "Louvre & Tuileries",
    address: "51 Galerie de Montpensier, 75001 Paris",
    lat: 48.86555,
    lng: 2.33738,
    drinks: ["Matcha latte", "Coffee"],
    notes: "Small coffee bar inside the Palais-Royal gardens. Fox-shaped biscuits.",
    hours: "Mon–Sat 9:00–18:30, Sun 10:00–18:30",
    open: "09:00-18:30",
    openOn: {"sun": "10:00-18:30"},
    status: "want",
    tags: ["matcha", "coffee", "instagram"],
  },
  {
    id: "cafe-marly",
    name: "Le Café Marly",
    cat: "cafe",
    area: "Louvre & Tuileries",
    address: "93 Rue de Rivoli, 75001 Paris",
    lat: 48.86164,
    lng: 2.33593,
    notes: "Terrace under the Louvre arcades looking straight at the glass pyramid.",
    status: "want",
    tags: ["view", "terrace", "instagram"],
  },
  {
    id: "boot-cafe",
    name: "Boot Café",
    cat: "cafe",
    area: "Le Marais",
    address: "19 Rue du Pont aux Choux, 75003 Paris",
    lat: 48.86117,
    lng: 2.36533,
    drinks: ["Coffee", "Matcha"],
    notes: "Tiny coffee shop in a former cobbler's shop, with a blue shopfront.",
    status: "want",
    tags: ["coffee", "matcha", "instagram"],
  },
  {
    id: "ob-la-di",
    name: "Ob-La-Di",
    cat: "cafe",
    area: "Le Marais",
    address: "54 Rue de Saintonge, 75003 Paris",
    lat: 48.86301,
    lng: 2.36402,
    drinks: ["Matcha latte"],
    notes: "Small, bright café. Popular for matcha and brunch.",
    status: "want",
    tags: ["matcha", "coffee"],
  },
  {
    id: "cafeotheque",
    name: "La Caféothèque",
    cat: "cafe",
    area: "Le Marais",
    address: "52 Rue de l'Hôtel de Ville, 75004 Paris",
    lat: 48.85444,
    lng: 2.35584,
    notes: "Specialty coffee roaster by the Seine.",
    status: "want",
    tags: ["coffee"],
  },
  {
    id: "shakespeare-cafe",
    name: "Shakespeare and Company Café",
    cat: "cafe",
    area: "Latin Quarter",
    address: "37 Rue de la Bûcherie, 75005 Paris",
    lat: 48.85257,
    lng: 2.34711,
    notes: "Café beside the famous English bookshop, facing Notre-Dame.",
    status: "want",
    tags: ["coffee", "books"],
  },
  {
    id: "carette",
    name: "Carette Trocadéro",
    cat: "cafe",
    area: "Eiffel Tower & Trocadéro",
    address: "4 Place du Trocadéro et du 11 Novembre, 75016 Paris",
    lat: 48.86284,
    lng: 2.28714,
    order: ["Macarons"],
    notes: "Classic tea room near the Trocadéro. Good stop before Eiffel Tower photos.",
    status: "want",
    tags: ["pastry", "macarons", "terrace"],
  },
  {
    id: "laduree-champs",
    name: "Ladurée Champs-Élysées",
    cat: "cafe",
    area: "Champs-Élysées",
    address: "75 Avenue des Champs-Élysées, 75008 Paris",
    lat: 48.87089,
    lng: 2.303,
    order: ["Macarons"],
    notes: "The famous macaron house in its grand tea-room setting.",
    status: "want",
    tags: ["macarons", "instagram", "rainy"],
  },

  // ── Pastry ──
  {
    id: "pierre-herme-bonaparte",
    name: "Pierre Hermé",
    cat: "pastry",
    area: "Saint-Germain",
    address: "72 Rue Bonaparte, 75006 Paris",
    lat: 48.85147,
    lng: 2.33278,
    order: ["Ispahan (rose, lychee, raspberry)", "Macarons: Ispahan, Mogador, Mosaïc"],
    notes: "Ranked best pâtisserie in the world by La Liste 2026. Takeaway shop.",
    status: "want",
    tags: ["macarons", "top pick"],
  },
  {
    id: "laduree-royale",
    name: "Ladurée Royale",
    cat: "pastry",
    area: "Opéra",
    address: "16 Rue Royale, 75008 Paris",
    lat: 48.86843,
    lng: 2.32361,
    order: ["Macarons: salted caramel, pistachio", "Ispahan"],
    notes: "The original Ladurée shop and tea room. The prettiest pastel macarons and boxes.",
    status: "want",
    tags: ["macarons", "instagram", "tea room", "rainy"],
  },
  {
    id: "carette-vosges",
    name: "Carette Place des Vosges",
    cat: "pastry",
    area: "Le Marais",
    address: "25 Place des Vosges, 75003 Paris",
    lat: 48.85635,
    lng: 2.36547,
    order: ["Macarons", "Millefeuille"],
    notes: "Tea room under the arcades of Place des Vosges. Some say the best macarons in Paris, with a crunchier bite.",
    status: "want",
    tags: ["macarons", "tea room", "terrace"],
  },
  {
    id: "dalloyau",
    name: "Dalloyau",
    cat: "pastry",
    area: "Champs-Élysées",
    address: "101 Rue du Faubourg Saint-Honoré, 75008 Paris",
    lat: 48.87229,
    lng: 2.31195,
    order: ["Opéra cake", "Macarons"],
    notes: "Historic pastry house dating back to 1682. Home of the Opéra cake.",
    status: "want",
    tags: ["macarons", "historic"],
  },
  {
    id: "stohrer",
    name: "Stohrer",
    cat: "pastry",
    area: "Montorgueil & Les Halles",
    address: "51 Rue Montorgueil, 75002 Paris",
    lat: 48.86525,
    lng: 2.34682,
    order: ["Baba au rhum", "Puits d'amour", "Éclairs"],
    notes: "The oldest pâtisserie in Paris, founded in 1730. The baba au rhum was created here. Beautiful painted interior.",
    status: "want",
    tags: ["baba au rhum", "éclairs", "historic", "instagram"],
  },
  {
    id: "fou-de-patisserie",
    name: "Fou de Pâtisserie",
    cat: "pastry",
    area: "Montorgueil & Les Halles",
    address: "45 Rue Montorgueil, 75002 Paris",
    lat: 48.86493,
    lng: 2.34671,
    order: ["Pastries from top Paris chefs"],
    notes: "One shop selling pastries from many of the city's best chefs. Good for trying several in one stop.",
    status: "want",
    tags: ["fruit pastries", "éclairs", "millefeuille"],
  },
  {
    id: "cedric-grolet-opera",
    name: "Cédric Grolet Opéra",
    cat: "pastry",
    area: "Opéra",
    address: "35 Avenue de l'Opéra, 75002 Paris",
    lat: 48.86796,
    lng: 2.3332,
    order: ["Trompe-l'œil fruit pastries", "Croissant"],
    notes: "Pastries that look exactly like real fruit. Very Instagrammable. Expect a queue.",
    status: "want",
    tags: ["fruit pastries", "croissants", "instagram", "top pick"],
  },
  {
    id: "ritz-comptoir",
    name: "Ritz Paris Le Comptoir",
    cat: "pastry",
    area: "Opéra",
    address: "38 Rue Cambon, 75001 Paris",
    lat: 48.86888,
    lng: 2.32759,
    order: ["Madeleines", "Marbled cake"],
    notes: "Small pastry counter of the Ritz hotel, at the back on Rue Cambon. Known for its madeleines.",
    status: "want",
    tags: ["madeleines", "luxury"],
  },
  {
    id: "eclair-de-genie",
    name: "L'Éclair de Génie",
    cat: "pastry",
    area: "Le Marais",
    address: "14 Rue Pavée, 75004 Paris",
    lat: 48.8562,
    lng: 2.36062,
    order: ["Éclairs"],
    notes: "Rows of colourful éclairs in many flavours.",
    status: "want",
    tags: ["éclairs", "instagram"],
  },
  {
    id: "jacques-genin",
    name: "Jacques Genin",
    cat: "pastry",
    area: "Le Marais",
    address: "133 Rue de Turenne, 75003 Paris",
    lat: 48.86447,
    lng: 2.36462,
    order: ["Millefeuille, made to order", "Caramels"],
    notes: "Chocolatier famous for a millefeuille assembled when you order it, plus soft caramels.",
    status: "want",
    tags: ["millefeuille", "chocolate", "caramels"],
  },
  {
    id: "sebastien-gaudard",
    name: "Sébastien Gaudard",
    cat: "pastry",
    area: "Pigalle & Rue des Martyrs",
    address: "22 Rue des Martyrs, 75009 Paris",
    lat: 48.87809,
    lng: 2.33967,
    order: ["Paris-Brest", "Millefeuille"],
    notes: "Classic French pastries done perfectly, in a pretty old-style shop.",
    status: "want",
    tags: ["millefeuille", "choux", "classic"],
  },
  {
    id: "mamiche",
    name: "Mamiche",
    cat: "pastry",
    area: "Pigalle & Rue des Martyrs",
    address: "45 Rue Condorcet, 75009 Paris",
    lat: 48.88014,
    lng: 2.34353,
    order: ["Babka", "Cream puffs"],
    notes: "Popular neighbourhood bakery. Known for chocolate babka and cream puffs.",
    status: "want",
    tags: ["choux", "viennoiserie"],
  },
  {
    id: "odette",
    name: "Odette",
    cat: "pastry",
    area: "Latin Quarter",
    address: "77 Rue Galande, 75005 Paris",
    lat: 48.85206,
    lng: 2.34651,
    order: ["Choux cream puffs"],
    notes: "Cream puffs in a little green-and-white house across the river from Notre-Dame.",
    status: "want",
    tags: ["choux", "instagram"],
  },
  {
    id: "aki-boulangerie",
    name: "Aki Boulangerie",
    cat: "pastry",
    area: "Little Tokyo",
    address: "16 Rue Sainte-Anne, 75001 Paris",
    lat: 48.8661,
    lng: 2.33549,
    order: ["Matcha pastries", "Melon pan", "Onigiri"],
    notes: "Japanese-French bakery on Rue Sainte-Anne. Matcha viennoiseries and bento lunches.",
    status: "want",
    tags: ["japanese", "matcha", "viennoiserie"],
  },
  {
    id: "du-pain-et-des-idees",
    name: "Du Pain et des Idées",
    cat: "pastry",
    area: "Canal Saint-Martin",
    address: "34 Rue Yves Toudic, 75010 Paris",
    lat: 48.8712,
    lng: 2.36289,
    order: ["Pistachio-chocolate escargot", "Pain des amis"],
    notes: "Bakery known for the pistachio-chocolate escargot pastry. Takeaway only.",
    hours: "Closed weekends",
    closed: ["sat", "sun"],
    status: "want",
    tags: ["viennoiserie", "croissants", "top pick"],
  },
  {
    id: "la-parisienne",
    name: "La Parisienne",
    cat: "pastry",
    area: "Grands Boulevards",
    address: "12 Rue du Faubourg Poissonnière, 75010 Paris",
    lat: 48.8716,
    lng: 2.34805,
    order: ["Butter croissant", "Pain au chocolat"],
    notes: "2nd place, Best Butter Croissant of Greater Paris 2025.",
    status: "want",
    tags: ["croissants", "pain au chocolat", "award"],
  },
  {
    id: "mille-et-un",
    name: "Boulangerie Mille et Un",
    cat: "pastry",
    area: "Saint-Germain",
    address: "32 Rue Saint-Placide, 75006 Paris",
    lat: 48.84865,
    lng: 2.32551,
    order: ["Butter croissant", "Pain au chocolat"],
    notes: "3rd place, Best Butter Croissant of Greater Paris 2025.",
    status: "want",
    tags: ["croissants", "pain au chocolat", "award"],
  },
  {
    id: "rabineau",
    name: "Boulangerie Moderne Rabineau",
    cat: "pastry",
    area: "Latin Quarter",
    address: "16 Rue des Fossés-Saint-Jacques, 75005 Paris",
    lat: 48.84549,
    lng: 2.34428,
    order: ["Butter croissant"],
    notes: "4th place, Best Butter Croissant of Greater Paris 2025. Near the Panthéon.",
    status: "want",
    tags: ["croissants", "award"],
  },
  {
    id: "utopie",
    name: "Boulangerie Utopie",
    cat: "pastry",
    area: "Bastille & 11th",
    address: "20 Rue Jean-Pierre Timbaud, 75011 Paris",
    lat: 48.86534,
    lng: 2.36874,
    order: ["Croissant", "Black sesame éclair"],
    notes: "Creative bakery loved for its croissants and unusual flavours.",
    status: "want",
    tags: ["croissants", "éclairs", "viennoiserie"],
  },

  // ── Shop ──
  {
    id: "repetto",
    name: "Repetto",
    cat: "shop",
    area: "Opéra",
    address: "22 Rue de la Paix, 75002 Paris",
    lat: 48.8698,
    lng: 2.33195,
    notes: "The original Repetto shop, open since 1959 next to the Opéra. Famous ballet flats, including the 'Cendrillon' made for Brigitte Bardot.",
    status: "want",
    tags: ["shoes", "fashion", "instagram"],
  },
  {
    id: "buly",
    name: "Officine Universelle Buly",
    cat: "shop",
    area: "Saint-Germain",
    address: "6 Rue Bonaparte, 75006 Paris",
    lat: 48.85719,
    lng: 2.33501,
    notes: "Beautiful old-apothecary-style shop. Combs (including Japanese boxwood), brushes, soaps and perfumes. Ask about name calligraphy on your purchase.",
    status: "want",
    tags: ["hair", "beauty", "instagram"],
  },
  {
    id: "maison-caillau",
    name: "Maison Caillau",
    cat: "shop",
    area: "Champs-Élysées",
    address: "124 Rue du Faubourg Saint-Honoré, 75008 Paris",
    lat: 48.87212,
    lng: 2.31326,
    notes: "French artisan hair accessories: combs, hair clips, headbands and bows.",
    hours: "Mon–Sat 10:00–19:00",
    open: "10:00-19:00",
    closed: ["sun"],
    status: "want",
    tags: ["hair", "fashion"],
  },
  {
    id: "la-bonne-brosse",
    name: "La Bonne Brosse",
    cat: "shop",
    area: "Louvre & Tuileries",
    address: "18 Rue de Richelieu, 75001 Paris",
    lat: 48.86468,
    lng: 2.33641,
    notes: "Handmade hairbrushes and combs.",
    status: "want",
    tags: ["hair", "beauty"],
  },
  {
    id: "alexandre-de-paris",
    name: "Alexandre de Paris",
    cat: "shop",
    area: "Louvre & Tuileries",
    address: "La Samaritaine, 9 Rue de la Monnaie, 75001 Paris",
    lat: 48.85921,
    lng: 2.34235,
    notes: "Hair clips, barrettes and combs made in France, inside La Samaritaine.",
    status: "want",
    tags: ["hair", "fashion"],
  },
  {
    id: "samaritaine",
    name: "La Samaritaine",
    cat: "shop",
    area: "Louvre & Tuileries",
    address: "9 Rue de la Monnaie, 75001 Paris",
    lat: 48.85921,
    lng: 2.34235,
    notes: "Art Nouveau department store by the Pont Neuf, with a glass roof and peacock frieze.",
    status: "want",
    tags: ["department store", "fashion", "beauty", "instagram", "rainy"],
  },
  {
    id: "bon-marche",
    name: "Le Bon Marché",
    cat: "shop",
    area: "Saint-Germain",
    address: "24 Rue de Sèvres, 75007 Paris",
    lat: 48.85104,
    lng: 2.32413,
    notes: "The most elegant department store in Paris. Fashion, beauty and the famous escalators.",
    status: "want",
    tags: ["department store", "fashion", "beauty", "rainy"],
  },
  {
    id: "grande-epicerie",
    name: "La Grande Épicerie de Paris",
    cat: "shop",
    area: "Saint-Germain",
    address: "38 Rue de Sèvres, 75007 Paris",
    lat: 48.84997,
    lng: 2.3233,
    notes: "Huge luxury food hall next to Le Bon Marché. The best place for food gifts: chocolate, jams, salted butter caramel.",
    status: "want",
    tags: ["food & gifts", "rainy"],
  },
  {
    id: "citypharma",
    name: "Citypharma",
    cat: "shop",
    area: "Saint-Germain",
    address: "26 Rue du Four, 75006 Paris",
    lat: 48.85272,
    lng: 2.33339,
    notes: "The famous cheap pharmacy for French skincare (La Roche-Posay, Avène, Caudalie, Nuxe). Very busy, so go early.",
    hours: "Open every day, Sundays until 20:00",
    status: "want",
    tags: ["beauty"],
  },
  {
    id: "diptyque",
    name: "Diptyque",
    cat: "shop",
    area: "Latin Quarter",
    address: "34 Boulevard Saint-Germain, 75005 Paris",
    lat: 48.84968,
    lng: 2.35166,
    notes: "The original Diptyque shop, since 1961. Candles and perfume.",
    status: "want",
    tags: ["beauty", "home"],
  },
  {
    id: "merci",
    name: "Merci",
    cat: "shop",
    area: "Le Marais",
    address: "111 Boulevard Beaumarchais, 75003 Paris",
    lat: 48.86072,
    lng: 2.36703,
    notes: "Concept store with fashion, home goods and a café. The red Fiat in the courtyard is the photo.",
    status: "want",
    tags: ["fashion", "home", "instagram"],
  },
  {
    id: "mariage-freres",
    name: "Mariage Frères",
    cat: "shop",
    area: "Le Marais",
    address: "30 Rue du Bourg-Tibourg, 75004 Paris",
    lat: 48.85769,
    lng: 2.35649,
    notes: "Historic French tea house with a shop and a colonial-style tea room.",
    status: "want",
    tags: ["food & gifts", "tea room"],
  },
  {
    id: "sezane",
    name: "Sézane L'Appartement",
    cat: "shop",
    area: "Grands Boulevards",
    address: "1 Rue Saint-Fiacre, 75002 Paris",
    lat: 48.86959,
    lng: 2.3451,
    notes: "The Paris flagship of the French fashion brand, set up like an apartment.",
    status: "want",
    tags: ["fashion"],
  },
  {
    id: "dehillerin",
    name: "E.Dehillerin",
    cat: "shop",
    area: "Montorgueil & Les Halles",
    address: "18 Rue Coquillière, 75001 Paris",
    lat: 48.86379,
    lng: 2.34281,
    notes: "Old chef's cookware shop, open since 1820. Copper pans and kitchen tools.",
    status: "want",
    tags: ["home"],
  },
  {
    id: "shakespeare-books",
    name: "Shakespeare and Company",
    cat: "shop",
    area: "Latin Quarter",
    address: "37 Rue de la Bûcherie, 75005 Paris",
    lat: 48.85257,
    lng: 2.34711,
    notes: "The famous English-language bookshop facing Notre-Dame.",
    status: "want",
    tags: ["books", "instagram", "rainy"],
  },
  {
    id: "enfants-rouges",
    name: "Marché des Enfants Rouges",
    cat: "shop",
    area: "Le Marais",
    address: "39 Rue de Bretagne, 75003 Paris",
    lat: 48.86279,
    lng: 2.36198,
    notes: "The oldest covered market in Paris, with food stalls for lunch.",
    hours: "Closed Mondays",
    closed: ["mon"],
    status: "want",
    tags: ["markets", "cheap"],
  },
  {
    id: "saint-ouen",
    name: "Marché aux Puces de Saint-Ouen",
    cat: "shop",
    area: "Saint-Ouen (flea market)",
    address: "Rue des Rosiers, 93400 Saint-Ouen",
    lat: 48.90652,
    lng: 2.33547,
    notes: "The biggest antiques and flea market in the world. Open Saturday to Monday, so Saturday 31 Oct or Sunday 1 Nov fit your trip.",
    hours: "Saturday to Monday",
    closed: ["tue", "wed", "thu", "fri"],
    status: "want",
    tags: ["markets", "vintage"],
  },
  {
    id: "tang-freres",
    name: "Tang Frères",
    cat: "shop",
    area: "Chinatown",
    address: "48 Avenue d'Ivry, 75013 Paris",
    lat: 48.82424,
    lng: 2.36517,
    notes: "Huge Asian supermarket. Fun for snacks and sweets.",
    status: "want",
    tags: ["food & gifts"],
  },

  // ── Go ──
  {
    id: "galerie-dior",
    name: "La Galerie Dior",
    cat: "go",
    area: "Champs-Élysées",
    address: "11 Rue François 1er, 75008 Paris",
    lat: 48.867,
    lng: 2.3047,
    notes: "Dior exhibition. Booked for 30 Oct at 12:30.",
    hours: "11:00 – 19:00, last entry 17:30. Closed Tuesdays.",
    open: "11:00-19:00",
    closed: ["tue"],
    status: "want",
    tags: ["fashion", "museum", "rainy"],
  },
  {
    id: "louvre",
    name: "Louvre",
    cat: "go",
    area: "Louvre & Tuileries",
    address: "Rue de Rivoli, 75001 Paris",
    lat: 48.85978,
    lng: 2.34442,
    notes: "To book. Date not chosen yet.",
    hours: "9:00 – 18:00, Wed and Fri until 21:00. Closed Tuesdays.",
    open: "09:00-18:00",
    openOn: {"wed": "09:00-21:00", "fri": "09:00-21:00"},
    closed: ["tue"],
    bookingUrl: "https://www.louvre.fr",
    bookAhead: "Book a timed ticket online. Popular slots sell out days ahead.",
    status: "want",
    tags: ["museum", "landmark", "to book", "rainy"],
  },
  {
    id: "versailles",
    name: "Palace of Versailles",
    cat: "go",
    area: "Versailles (day trip)",
    address: "Place d'Armes, 78000 Versailles",
    lat: 48.80384,
    lng: 2.12465,
    notes: "To book. Date not chosen yet. Plan for most of a day.",
    hours: "Closed Mondays",
    closed: ["mon"],
    bookingUrl: "https://www.chateauversailles.fr",
    bookAhead: "Book a timed ticket online and go early.",
    status: "want",
    tags: ["landmark", "day trip", "to book"],
  },
  {
    id: "orsay",
    name: "Musée d'Orsay",
    cat: "go",
    area: "Saint-Germain",
    address: "Esplanade Valéry Giscard d'Estaing, 75007 Paris",
    lat: 48.86001,
    lng: 2.32522,
    notes: "Impressionists in a former railway station. Don't miss the giant clock window on the 5th floor, looking over the Seine to Sacré-Cœur.",
    bestTime: "Thursday evening is quieter",
    hours: "9:30 – 18:00, Thu until 21:45. Closed Mondays.",
    open: "09:30-18:00",
    openOn: {"thu": "09:30-21:45"},
    closed: ["mon"],
    status: "maybe",
    tags: ["museum", "view", "instagram", "rainy"],
  },
  {
    id: "eiffel-tower",
    name: "Eiffel Tower",
    cat: "go",
    area: "Eiffel Tower & Trocadéro",
    address: "Champ de Mars, 5 Avenue Anatole France, 75007 Paris",
    lat: 48.8584,
    lng: 2.2945,
    notes: "The view from the top is the classic one.",
    bestTime: "After dark it sparkles for 5 minutes every hour on the hour",
    bookingUrl: "https://www.toureiffel.paris",
    bookAhead: "Book summit tickets on the official site. They sell out.",
    status: "want",
    tags: ["landmark", "view", "to book"],
  },
  {
    id: "trocadero",
    name: "Trocadéro",
    cat: "go",
    area: "Eiffel Tower & Trocadéro",
    address: "Place du Trocadéro et du 11 Novembre, 75016 Paris",
    lat: 48.86284,
    lng: 2.28714,
    notes: "The best classic view and photo of the Eiffel Tower. Free.",
    bestTime: "Early morning for no crowds, or on the hour after dark for the sparkle",
    status: "want",
    tags: ["view", "instagram", "free", "landmark"],
  },
  {
    id: "bir-hakeim",
    name: "Pont de Bir-Hakeim",
    cat: "go",
    area: "Eiffel Tower & Trocadéro",
    address: "Pont de Bir-Hakeim, 75015 Paris",
    lat: 48.85573,
    lng: 2.28755,
    notes: "Two-level bridge with an iron colonnade and an Eiffel Tower view. A popular photo spot.",
    bestTime: "Morning light",
    status: "want",
    tags: ["instagram", "free", "view"],
  },
  {
    id: "invalides",
    name: "Les Invalides (Napoleon's tomb)",
    cat: "go",
    area: "Eiffel Tower & Trocadéro",
    address: "129 Rue de Grenelle, 75007 Paris",
    lat: 48.85704,
    lng: 2.31188,
    notes: "Golden dome with Napoleon's tomb and the army museum.",
    status: "want",
    tags: ["museum", "landmark", "rainy"],
  },
  {
    id: "sacre-coeur",
    name: "Sacré-Cœur",
    cat: "go",
    area: "Montmartre",
    address: "35 Rue du Chevalier de la Barre, 75018 Paris",
    lat: 48.88711,
    lng: 2.34349,
    notes: "White basilica on the hill with a panoramic view over Paris from the steps. Free entry.",
    bestTime: "Sunset from the steps",
    status: "want",
    tags: ["view", "church", "free", "landmark"],
  },
  {
    id: "place-du-tertre",
    name: "Place du Tertre",
    cat: "go",
    area: "Montmartre",
    address: "Place du Tertre, 75018 Paris",
    lat: 48.88653,
    lng: 2.3408,
    notes: "Square full of painters, 2 minutes from Sacré-Cœur. Walk on to Rue de l'Abreuvoir and La Maison Rose.",
    status: "want",
    tags: ["free"],
  },
  {
    id: "moulin-rouge",
    name: "Moulin Rouge",
    cat: "go",
    area: "Pigalle & Rue des Martyrs",
    address: "82 Boulevard de Clichy, 75018 Paris",
    lat: 48.88411,
    lng: 2.33236,
    notes: "The red windmill. Free to see from outside.",
    bestTime: "After dark, when it's lit up",
    status: "want",
    tags: ["instagram", "landmark", "free"],
  },
  {
    id: "notre-dame",
    name: "Notre-Dame",
    cat: "go",
    area: "Île de la Cité",
    address: "6 Parvis Notre-Dame, 75004 Paris",
    lat: 48.85294,
    lng: 2.35005,
    notes: "Reopened after the restoration. Entry is free. Other sites selling tickets are not official.",
    hours: "Weekdays 7:50–19:00 (Thu until 22:00), weekends 8:15–19:30",
    open: "07:50-19:00",
    openOn: {"thu": "07:50-22:00", "sat": "08:15-19:30", "sun": "08:15-19:30"},
    bookingUrl: "https://www.notredamedeparis.fr",
    bookAhead: "Free time-slot reservation opens 48 hours ahead. Only use notredamedeparis.fr.",
    status: "want",
    tags: ["church", "free", "landmark", "to book", "rainy"],
  },
  {
    id: "sainte-chapelle",
    name: "Sainte-Chapelle",
    cat: "go",
    area: "Île de la Cité",
    address: "10 Boulevard du Palais, 75001 Paris",
    lat: 48.85504,
    lng: 2.34536,
    notes: "Chapel with floor-to-ceiling stained glass.",
    bestTime: "A sunny day, when the light comes through the glass",
    bookingUrl: "https://www.sainte-chapelle.fr",
    bookAhead: "Book a time slot online.",
    status: "want",
    tags: ["church", "instagram", "to book", "rainy"],
  },
  {
    id: "arc-de-triomphe",
    name: "Arc de Triomphe",
    cat: "go",
    area: "Champs-Élysées",
    address: "Place Charles de Gaulle, 75008 Paris",
    lat: 48.87377,
    lng: 2.29544,
    notes: "Climb to the rooftop for a view down the Champs-Élysées to the Eiffel Tower. Use the underground passage to cross.",
    bestTime: "Sunset",
    status: "want",
    tags: ["view", "landmark"],
  },
  {
    id: "champs-elysees",
    name: "Champs-Élysées",
    cat: "go",
    area: "Champs-Élysées",
    address: "Avenue des Champs-Élysées, 75008 Paris",
    lat: 48.8715,
    lng: 2.30222,
    notes: "Walk from the Arc de Triomphe down towards Place de la Concorde.",
    status: "want",
    tags: ["free", "landmark"],
  },
  {
    id: "musee-ysl",
    name: "Musée Yves Saint Laurent",
    cat: "go",
    area: "Champs-Élysées",
    address: "5 Avenue Marceau, 75116 Paris",
    lat: 48.8656,
    lng: 2.29954,
    notes: "YSL's former couture house. A good match with the Dior gallery.",
    hours: "Closed Mondays",
    closed: ["mon"],
    status: "want",
    tags: ["fashion", "museum", "rainy"],
  },
  {
    id: "pont-alexandre-iii",
    name: "Pont Alexandre III",
    cat: "go",
    area: "Champs-Élysées",
    address: "Pont Alexandre III, 75008 Paris",
    lat: 48.86347,
    lng: 2.31352,
    notes: "The most ornate bridge in Paris, with gold statues and an Eiffel Tower view.",
    bestTime: "Sunset",
    status: "want",
    tags: ["instagram", "free", "view"],
  },
  {
    id: "palais-garnier",
    name: "Palais Garnier",
    cat: "go",
    area: "Opéra",
    address: "Place de l'Opéra, 75009 Paris",
    lat: 48.87079,
    lng: 2.33251,
    notes: "The opera house. The grand staircase and foyer are open for visits.",
    status: "want",
    tags: ["landmark", "instagram", "rainy"],
  },
  {
    id: "galeries-lafayette",
    name: "Galeries Lafayette",
    cat: "go",
    area: "Opéra",
    address: "40 Boulevard Haussmann, 75009 Paris",
    lat: 48.87365,
    lng: 2.33213,
    notes: "See the stained-glass dome inside, then go up to the free rooftop terrace for the view.",
    bestTime: "Sunset on the rooftop",
    status: "want",
    tags: ["view", "free", "instagram", "rainy", "department store"],
  },
  {
    id: "orangerie",
    name: "Musée de l'Orangerie",
    cat: "go",
    area: "Louvre & Tuileries",
    address: "Jardin des Tuileries, 75001 Paris",
    lat: 48.86281,
    lng: 2.32531,
    notes: "Monet's Water Lilies in two oval rooms. Small, about 1 hour.",
    hours: "9:00 – 18:00. Closed Tuesdays.",
    open: "09:00-18:00",
    closed: ["tue"],
    status: "want",
    tags: ["museum", "rainy"],
  },
  {
    id: "tuileries",
    name: "Jardin des Tuileries",
    cat: "go",
    area: "Louvre & Tuileries",
    address: "Place de la Concorde to the Louvre, 75001 Paris",
    lat: 48.8635,
    lng: 2.3275,
    notes: "Garden between the Louvre and Place de la Concorde. Good walk between museums.",
    status: "want",
    tags: ["garden", "free"],
  },
  {
    id: "palais-royal",
    name: "Palais-Royal gardens",
    cat: "go",
    area: "Louvre & Tuileries",
    address: "8 Rue de Montpensier, 75001 Paris",
    lat: 48.86517,
    lng: 2.33699,
    notes: "Quiet garden with the black-and-white striped columns, a popular photo spot. Café Kitsuné is here.",
    status: "want",
    tags: ["garden", "instagram", "free"],
  },
  {
    id: "galerie-vivienne",
    name: "Galerie Vivienne",
    cat: "go",
    area: "Louvre & Tuileries",
    address: "4 Rue des Petits Champs, 75002 Paris",
    lat: 48.86629,
    lng: 2.33984,
    notes: "The prettiest covered passage, with a mosaic floor and glass roof.",
    status: "want",
    tags: ["instagram", "rainy", "free"],
  },
  {
    id: "passage-panoramas",
    name: "Passage des Panoramas",
    cat: "go",
    area: "Grands Boulevards",
    address: "11 Boulevard Montmartre, 75002 Paris",
    lat: 48.87152,
    lng: 2.34192,
    notes: "The oldest covered passage in Paris (1799). Small restaurants and old stamp shops.",
    status: "want",
    tags: ["rainy", "free"],
  },
  {
    id: "place-des-vosges",
    name: "Place des Vosges",
    cat: "go",
    area: "Le Marais",
    address: "Place des Vosges, 75004 Paris",
    lat: 48.85563,
    lng: 2.36553,
    notes: "The oldest planned square in Paris, with red-brick arcades. Start a Marais walk here.",
    status: "want",
    tags: ["free"],
  },
  {
    id: "luxembourg",
    name: "Jardin du Luxembourg",
    cat: "go",
    area: "Saint-Germain",
    address: "Rue de Médicis, 75006 Paris",
    lat: 48.84899,
    lng: 2.33883,
    notes: "Palace gardens with the pond and green chairs.",
    status: "want",
    tags: ["garden", "free"],
  },
  {
    id: "rue-cremieux",
    name: "Rue Crémieux",
    cat: "go",
    area: "Bastille & Gare de Lyon",
    address: "Rue Crémieux, 75012 Paris",
    lat: 48.84688,
    lng: 2.37087,
    notes: "Pedestrian street of pastel houses. People live here, so keep it quiet.",
    bestTime: "Morning, when it's quiet",
    status: "want",
    tags: ["instagram", "free"],
  },
  {
    id: "chinatown",
    name: "Chinatown",
    cat: "go",
    area: "Chinatown",
    address: "Avenue de Choisy, 75013 Paris",
    lat: 48.82309,
    lng: 2.36234,
    notes: "Europe's largest Chinatown, between Avenue de Choisy and Avenue d'Ivry. Pho, dim sum, bubble tea and the Tang Frères supermarket.",
    status: "want",
    tags: ["neighbourhood", "free"],
  },
  {
    id: "little-tokyo",
    name: "Little Tokyo (Rue Sainte-Anne)",
    cat: "go",
    area: "Little Tokyo",
    address: "Rue Sainte-Anne, 75001 Paris",
    lat: 48.86638,
    lng: 2.33557,
    notes: "The Japanese quarter: ramen, udon, Japanese bakeries and grocery shops, with Korean spots on the side streets.",
    status: "want",
    tags: ["neighbourhood"],
  },
  {
    id: "belleville",
    name: "Belleville",
    cat: "go",
    area: "Belleville",
    address: "Rue de Belleville, 75020 Paris",
    lat: 48.87284,
    lng: 2.37981,
    notes: "Paris's second Chinatown, with street art on Rue Dénoyez and the Parc de Belleville view.",
    status: "want",
    tags: ["neighbourhood", "free"],
  },
  {
    id: "little-india",
    name: "Little India (Passage Brady)",
    cat: "go",
    area: "Grands Boulevards",
    address: "46 Rue du Faubourg Saint-Denis, 75010 Paris",
    lat: 48.8716,
    lng: 2.35377,
    notes: "Covered passage full of Indian restaurants.",
    status: "want",
    tags: ["neighbourhood"],
  },
  {
    id: "parc-de-belleville",
    name: "Parc de Belleville",
    cat: "go",
    area: "Belleville",
    address: "47 Rue des Couronnes, 75020 Paris",
    lat: 48.87008,
    lng: 2.38374,
    notes: "Hillside park with one of the best free views over Paris to the Eiffel Tower.",
    bestTime: "Sunset",
    status: "want",
    tags: ["view", "free", "garden"],
  },

  // ── Do ──
  {
    id: "seine-cruise",
    name: "Seine river cruise",
    cat: "do",
    area: "Eiffel Tower & Trocadéro",
    address: "Port de la Bourdonnais, 75007 Paris",
    lat: 48.8605,
    lng: 2.29399,
    notes: "About 1 hour on the river past the main sights.",
    bestTime: "Evening, when the Eiffel Tower is lit",
    status: "want",
    tags: ["boat", "evening", "view"],
  },
  {
    id: "marais-walk",
    name: "Walk around Le Marais",
    cat: "do",
    area: "Le Marais",
    address: "Place des Vosges, 75004 Paris",
    lat: 48.85563,
    lng: 2.36553,
    notes: "Small streets, boutiques and cafés. Go from Place des Vosges to Rue des Rosiers and Rue de Bretagne.",
    status: "want",
    tags: ["walk", "free"],
  },
  {
    id: "montmartre-walk",
    name: "Walk around Montmartre",
    cat: "do",
    area: "Montmartre",
    address: "Place des Abbesses, 75018 Paris",
    lat: 48.8844,
    lng: 2.33839,
    notes: "Go from Abbesses up to Sacré-Cœur, Place du Tertre, Rue de l'Abreuvoir and La Maison Rose. Take the funicular if you're tired.",
    status: "want",
    tags: ["walk", "free", "instagram"],
  },
  {
    id: "canal-walk",
    name: "Walk along Canal Saint-Martin",
    cat: "do",
    area: "Canal Saint-Martin",
    address: "Quai de Valmy, 75010 Paris",
    lat: 48.87646,
    lng: 2.36435,
    notes: "Iron footbridges, locks and cafés along the water. Combine with Du Pain et des Idées.",
    status: "want",
    tags: ["walk", "free", "instagram"],
  },
  {
    id: "street-art-denoyez",
    name: "Street art on Rue Dénoyez",
    cat: "do",
    area: "Belleville",
    address: "Rue Dénoyez, 75020 Paris",
    lat: 48.87165,
    lng: 2.37852,
    notes: "A short street covered in ever-changing graffiti.",
    status: "want",
    tags: ["free", "instagram"],
  },
  {
    id: "moulin-rouge-show",
    name: "Moulin Rouge show",
    cat: "do",
    area: "Pigalle & Rue des Martyrs",
    address: "82 Boulevard de Clichy, 75018 Paris",
    lat: 48.88411,
    lng: 2.33236,
    notes: "The classic cabaret show.",
    bookingUrl: "https://www.moulinrouge.fr",
    bookAhead: "Book online well ahead. Evening shows sell out.",
    status: "maybe",
    tags: ["evening", "to book"],
  },
];

// Planned and booked things, shown in the calendar.
const EVENTS = [
  {
    id: "train-to-paris",
    date: "2026-10-28",
    start: "08:10",
    end: "11:43",
    title: "Eurostar to Paris",
    where: "Paris Gare du Nord",
    address: "18 Rue de Dunkerque, 75010 Paris",
    booked: true,
    details: [
      ["From", "Amsterdam Centraal 08:10"],
      ["To", "Paris Gare du Nord 11:43"],
      ["Class", "Eurostar Standard · direct, 3 h 33 min"],
      ["Coach", "17"],
      ["Seats", "31 and 32"],
    ],
    notes: "",
  },
  {
    id: "train-home",
    date: "2026-11-02",
    start: "18:15",
    end: "21:50",
    title: "Eurostar home",
    where: "Paris Gare du Nord",
    address: "18 Rue de Dunkerque, 75010 Paris",
    booked: true,
    details: [
      ["From", "Paris Gare du Nord 18:15"],
      ["To", "Amsterdam Centraal 21:50"],
      ["Class", "Eurostar Standard · direct, 3 h 35 min"],
      ["Coach", "16"],
      ["Seats", "31 and 32"],
    ],
    notes: "Gare du Nord is busy at rush hour. Leave enough time to get there with your bags.",
  },
  {
    id: "dior-exhibition",
    date: "2026-10-30",
    start: "12:30",
    title: "Dior exhibition",
    placeId: "galerie-dior",
    booked: true,
    confirmation: "",
    notes: "",
  },
];

// Notes shown on each day in the Plan tab.
const DAY_NOTES = {
  "2026-10-28": "Arrival day: train arrives at Gare du Nord at 11:43. Idea for lunch: Bouillon Chartier Gare de l'Est is a short walk from the station. The Louvre is open until 21:00 tonight.",
  "2026-10-29": "Thursday. Musée d'Orsay is open until 21:45 and Notre-Dame until 22:00, good for an evening visit.",
  "2026-10-30": "Friday. Dior exhibition at 12:30. The Louvre is open until 21:00.",
  "2026-10-31": "Saturday. Busiest day at museums and shops. L'As du Fallafel is closed. The Saint-Ouen flea market is open.",
  "2026-11-01": "Sunday and a public holiday (All Saints' Day). Many shops and some bakeries are closed; most museums and sights stay open. The Saint-Ouen flea market is open.",
  "2026-11-02": "Departure day: train leaves Gare du Nord at 18:15. Ask the hotel to keep your bags after check-out. Musée d'Orsay, Versailles, Musée Yves Saint Laurent and the Marché des Enfants Rouges are closed on Mondays."
};

// Info tab.
const INFO = {
  "sections": [
    {
      "id": "getting",
      "title": "Getting around",
      "c": "do",
      "items": [
        {
          "t": "Metro, RER and train ticket: €2.55",
          "d": "One ticket per journey anywhere in the Paris region (2026 price). Bus and tram tickets are €2.05. Paper tickets are gone: load tickets onto a Navigo Easy card (€2 at station counters and machines) or onto your phone in the Île-de-France Mobilités app."
        },
        {
          "t": "You can't tap a bank card at metro gates yet",
          "d": "Contactless bank cards only work on buses and a few lines for now. Buy a ticket first."
        },
        {
          "t": "Arriving at Gare du Nord",
          "d": "Your Eurostar arrives at Gare du Nord. From there, metro lines 4 and 5 and the RER B, D and E go across the city. The official taxi rank is outside the station; ignore anyone offering a ride inside."
        },
        {
          "t": "Taxis from the station",
          "d": "Taxis from Gare du Nord run on the meter (the fixed fares are only for the airports). Uber, Bolt and G7 also pick up here."
        },
        {
          "t": "Uber, Bolt and G7",
          "d": "All work in Paris. G7 is the main official taxi company and has its own app."
        },
        {
          "t": "Walking",
          "d": "Central Paris is compact. Most places in this app are 15–30 minutes apart on foot, and walking is often faster than the metro for short trips."
        },
        {
          "t": "Montmartre funicular",
          "d": "Takes you up the hill to Sacré-Cœur on a normal metro ticket."
        }
      ]
    },
    {
      "id": "know",
      "title": "Good to know",
      "c": "cafe",
      "items": [
        {
          "t": "Always say “Bonjour”",
          "d": "When you walk into a shop, café or bakery, say bonjour first. It makes a big difference to how you're treated."
        },
        {
          "t": "Tipping",
          "d": "Service is already included in the price. Round up or leave €1–2 for coffee, and 5–10% for great service at dinner if you like."
        },
        {
          "t": "Tap water is free",
          "d": "Ask for “une carafe d'eau” instead of bottled water."
        },
        {
          "t": "Coffee costs more at a table",
          "d": "Standing at the bar is cheaper than sitting at a table or on the terrace."
        },
        {
          "t": "Meal times",
          "d": "Lunch is 12:00–14:30 and dinner usually starts 19:30. Many restaurants close between lunch and dinner, but brasseries and bouillons serve all day."
        },
        {
          "t": "Museum closing days",
          "d": "The Louvre, Orangerie and Dior gallery close on Tuesdays. Musée d'Orsay, Versailles and Musée Yves Saint Laurent close on Mondays."
        },
        {
          "t": "Sunday 1 November is a public holiday",
          "d": "All Saints' Day. Many shops and some bakeries are closed. Most museums and sights stay open."
        },
        {
          "t": "Winter time",
          "d": "France changes to winter time on 25 October, before you arrive. Sunset is around 17:30, so plan views and photos for about 17:00."
        },
        {
          "t": "Plugs",
          "d": "Type E sockets, 230 V."
        },
        {
          "t": "What to drink",
          "d": "Café crème is coffee with milk, “un café” is an espresso. Try a kir (white wine with blackcurrant liqueur) or kir royal (with champagne) as an apéritif."
        }
      ]
    },
    {
      "id": "avoid",
      "title": "Tourist traps to avoid",
      "c": "drink",
      "items": [
        {
          "t": "Friendship-bracelet sellers",
          "d": "Mostly at the bottom of the Sacré-Cœur steps. They tie a bracelet on your wrist, then demand money. Keep your hands in your pockets and keep walking."
        },
        {
          "t": "Petition clipboards",
          "d": "People asking you to sign a petition near the Eiffel Tower and Louvre. It's a distraction for pickpocketing. Say no and walk on."
        },
        {
          "t": "The “found a gold ring” trick",
          "d": "Someone ‘finds’ a ring next to you and offers to sell it. It's fake."
        },
        {
          "t": "Shell games on bridges",
          "d": "The players in the crowd are part of the team. You can't win."
        },
        {
          "t": "Pickpockets",
          "d": "Most common on metro lines 1 and 4, the RER B, at Gare du Nord and around the Eiffel Tower. Don't leave your phone on a café table by the street."
        },
        {
          "t": "Unofficial taxis",
          "d": "Ignore anyone offering a ride inside the airport. Use the official taxi rank or an app."
        },
        {
          "t": "Restaurants right next to top sights",
          "d": "Places with picture menus and people inviting you in are usually poor value. Walk two streets away."
        },
        {
          "t": "Fake Notre-Dame tickets",
          "d": "Entry is free. Only reserve on notredamedeparis.fr."
        },
        {
          "t": "Currency exchange counters",
          "d": "Rates at airports and tourist areas are bad. Pay by card, and if a card machine asks, choose to pay in euros."
        }
      ]
    }
  ],
  "phrases": [
    {
      "fr": "Bonjour / Bonsoir",
      "say": "bohn-zhoor / bohn-swahr",
      "en": "Hello / Good evening. Say it when you walk in anywhere."
    },
    {
      "fr": "Merci (beaucoup)",
      "say": "mehr-see (boh-koo)",
      "en": "Thank you (very much)"
    },
    {
      "fr": "S'il vous plaît",
      "say": "seel voo pleh",
      "en": "Please"
    },
    {
      "fr": "Pardon / Excusez-moi",
      "say": "par-dohn / ex-kew-zay mwah",
      "en": "Sorry / Excuse me"
    },
    {
      "fr": "Parlez-vous anglais ?",
      "say": "par-lay voo ahn-gleh",
      "en": "Do you speak English?"
    },
    {
      "fr": "Une table pour deux, s'il vous plaît",
      "say": "ewn tah-bluh poor duh",
      "en": "A table for two, please"
    },
    {
      "fr": "Je voudrais…",
      "say": "zhuh voo-dreh",
      "en": "I would like…"
    },
    {
      "fr": "Deux croissants, s'il vous plaît",
      "say": "duh krwah-sahn",
      "en": "Two croissants, please"
    },
    {
      "fr": "Une boîte de macarons",
      "say": "ewn bwaht duh ma-ka-rohn",
      "en": "A box of macarons"
    },
    {
      "fr": "Un café / Un café crème",
      "say": "uhn ka-fay / ka-fay krem",
      "en": "An espresso / A coffee with milk"
    },
    {
      "fr": "Un chocolat chaud",
      "say": "uhn sho-ko-la shoh",
      "en": "A hot chocolate"
    },
    {
      "fr": "Une carafe d'eau",
      "say": "ewn ka-raf doh",
      "en": "A jug of tap water (free)"
    },
    {
      "fr": "Sur place / À emporter",
      "say": "sewr plahs / ah ahm-por-tay",
      "en": "To eat in / To take away"
    },
    {
      "fr": "L'addition, s'il vous plaît",
      "say": "la-dee-syohn",
      "en": "The bill, please"
    },
    {
      "fr": "C'est combien ?",
      "say": "say kohm-byan",
      "en": "How much is it?"
    },
    {
      "fr": "Où sont les toilettes ?",
      "say": "oo sohn lay twa-let",
      "en": "Where are the toilets?"
    },
    {
      "fr": "Je suis allergique à…",
      "say": "zhuh swee a-lehr-zheek ah",
      "en": "I'm allergic to…"
    },
    {
      "fr": "Au revoir, bonne journée",
      "say": "oh ruh-vwahr, bun zhoor-nay",
      "en": "Goodbye, have a good day"
    }
  ],
  "emergency": [
    {
      "num": "112",
      "t": "All emergencies",
      "d": "Works from any phone. English spoken."
    },
    {
      "num": "15",
      "t": "Medical emergency (SAMU)",
      "d": ""
    },
    {
      "num": "17",
      "t": "Police",
      "d": ""
    },
    {
      "num": "18",
      "t": "Fire brigade",
      "d": ""
    },
    {
      "num": "114",
      "t": "Emergency by text message",
      "d": "If you can't speak on the phone."
    }
  ]
};
