// ─────────────────────────────────────────────────────────────
// Trip content. This is the only file that holds your plans.
// ─────────────────────────────────────────────────────────────

const TRIP = {
  title: "Paris",
  start: "2026-10-28",
  end: "2026-11-02",    // departure day
  arrival:   { time: "11:43", where: "Gare du Nord" },
  departure: { time: "18:15", where: "Gare du Nord" },
  stay: null,           // hotel being booked: { name: "", address: "", phone: "", lat: 0, lng: 0 }
};

// cat: "eat" | "drink" | "cafe" | "pastry" | "shop" | "go" | "do"
// status: "want" | "maybe" | "skip"
// open: "HH:MM-HH:MM" every day · openOn: per-day hours · closed: days it's shut
// tags drive the filters and lists: "view", "instagram", "neighbourhood", "rainy", "free", "to book", …
const PLACES = [

  // ── Eat ──
  {
    id: "chartier-grands-boulevards",
    name: "Bouillon Chartier · Grands Boulevards",
    cat: "eat",
    area: "Grands Boulevards",
    address: "7 Rue du Faubourg Montmartre, 75009 Paris",
    lat: 48.872,
    lng: 2.3432,
    price: "€20–30 per person",
    order: ["Escargots", "Steak frites", "Boeuf bourguignon", "Chocolate mousse"],
    notes: "The original 1896 dining hall. Classic French dishes at low prices. No reservations, so expect a queue at peak times.",
    hours: "Every day 11:30 – midnight",
    open: "11:30-24:00",
    price: "€20–30 per person",
    status: "want",
    tags: ["french classics", "cheap", "instagram", "bouillon"],
  },
  {
    id: "chartier-montparnasse",
    name: "Bouillon Chartier · Montparnasse",
    cat: "eat",
    area: "Montparnasse",
    address: "59 Boulevard du Montparnasse, 75006 Paris",
    lat: 48.844,
    lng: 2.3245,
    price: "€20–30 per person",
    order: ["Escargots", "Steak frites", "Boeuf bourguignon", "Chocolate mousse"],
    notes: "Art Nouveau dining room. No reservations, so expect a queue at peak times.",
    hours: "Every day 11:30 – midnight",
    open: "11:30-24:00",
    price: "€20–30 per person",
    status: "want",
    tags: ["french classics", "cheap", "instagram", "bouillon"],
  },
  {
    id: "chartier-gare-de-lest",
    name: "Bouillon Chartier · Gare de l'Est",
    cat: "eat",
    area: "Canal Saint-Martin",
    address: "5 Rue du 8 Mai 1945, 75010 Paris",
    lat: 48.8758,
    lng: 2.3585,
    price: "€20–30 per person",
    order: ["Escargots", "Steak frites", "Boeuf bourguignon", "Chocolate mousse"],
    notes: "Opposite Gare de l'Est. No reservations.",
    hours: "Every day 11:30 – midnight",
    hoursSource: "osm",
    openOn: {"mon": "11:30-24:00", "tue": "11:30-24:00", "wed": "11:30-24:00", "thu": "11:30-24:00", "fri": "11:30-24:00", "sat": "11:30-24:00", "sun": "11:30-24:00"},
    price: "€20–30 per person",
    status: "want",
    tags: ["french classics", "cheap", "bouillon"],
  },
  {
    id: "les-philosophes",
    name: "Les Philosophes",
    cat: "eat",
    area: "Le Marais",
    address: "28 Rue Vieille du Temple, 75004 Paris",
    lat: 48.8571,
    lng: 2.3584,
    price: "€30–45 per person",
    order: ["French onion soup"],
    notes: "Marais bistro with a busy terrace. The French onion soup is the favourite.",
    hours: "Wed–Sun 09:00 – 02:00",
    hoursSource: "osm",
    openOn: {"wed": "09:00-02:00", "thu": "09:00-02:00", "fri": "09:00-02:00", "sat": "09:00-02:00", "sun": "09:00-02:00"},
    price: "€30–45 per person",
    status: "want",
    tags: ["french classics", "terrace"],
  },
  {
    id: "bistrot-paul-bert",
    name: "Bistrot Paul Bert",
    cat: "eat",
    area: "Bastille & 11th",
    address: "18 Rue Paul Bert, 75011 Paris",
    lat: 48.8524,
    lng: 2.383,
    price: "€60–80 per person",
    order: ["Steak au poivre with frites"],
    notes: "One of the most loved classic bistros in Paris. Book a table.",
    price: "€60–80 per person",
    status: "want",
    tags: ["french classics"],
  },
  {
    id: "fontaine-de-mars",
    name: "La Fontaine de Mars",
    cat: "eat",
    area: "Eiffel Tower & Trocadéro",
    address: "129 Rue Saint-Dominique, 75007 Paris",
    lat: 48.8575,
    lng: 2.302,
    price: "€50–70 per person",
    order: ["Duck confit", "Escargots"],
    notes: "Classic red-checked bistro a few minutes from the Eiffel Tower. Good to book.",
    price: "€50–70 per person",
    status: "want",
    tags: ["french classics"],
  },
  {
    id: "relais-entrecote",
    name: "Le Relais de l'Entrecôte",
    cat: "eat",
    area: "Saint-Germain",
    address: "20 Rue Saint-Benoît, 75006 Paris",
    lat: 48.855,
    lng: 2.333,
    price: "€35–45 per person",
    order: ["Steak frites with the house sauce"],
    notes: "Only one menu: salad, then steak frites with the secret house sauce, and a second serving. No reservations, so expect a queue.",
    hours: "Every day 11:45 – 14:30, 19:00 – 23:30",
    hoursSource: "osm",
    openOn: {"mon": "11:45-14:30,19:00-23:30", "tue": "11:45-14:30,19:00-23:30", "wed": "11:45-14:30,19:00-23:30", "thu": "11:45-14:30,19:00-23:30", "fri": "11:45-14:30,19:00-23:30", "sat": "11:45-14:30,19:00-23:30", "sun": "11:45-14:30,19:00-23:30"},
    price: "€35–45 per person",
    status: "want",
    tags: ["french classics"],
  },
  {
    id: "au-pied-de-cochon",
    name: "Au Pied de Cochon",
    cat: "eat",
    area: "Montorgueil & Les Halles",
    address: "6 Rue Coquillière, 75001 Paris",
    lat: 48.8634,
    lng: 2.3438,
    price: "€40–60 per person",
    order: ["French onion soup"],
    notes: "Classic brasserie near Les Halles, open late.",
    hours: "Open 24 hours",
    hoursSource: "osm",
    openOn: {"mon": "00:00-24:00", "tue": "00:00-24:00", "wed": "00:00-24:00", "thu": "00:00-24:00", "fri": "00:00-24:00", "sat": "00:00-24:00", "sun": "00:00-24:00"},
    price: "€40–60 per person",
    status: "want",
    tags: ["french classics", "late night"],
  },
  {
    id: "bouillon-julien",
    name: "Bouillon Julien",
    cat: "eat",
    area: "Grands Boulevards",
    address: "16 Rue du Faubourg Saint-Denis, 75010 Paris",
    lat: 48.871,
    lng: 2.3537,
    price: "€20–30 per person",
    order: ["Escargots", "Steak frites"],
    notes: "Stunning Art Nouveau dining room with bouillon prices.",
    hours: "Every day 11:45 – midnight",
    hoursSource: "osm",
    openOn: {"mon": "11:45-24:00", "tue": "11:45-24:00", "wed": "11:45-24:00", "thu": "11:45-24:00", "fri": "11:45-24:00", "sat": "11:45-24:00", "sun": "11:45-24:00"},
    price: "€20–30 per person",
    status: "want",
    tags: ["french classics", "cheap", "instagram"],
  },
  {
    id: "bouillon-pigalle",
    name: "Bouillon Pigalle",
    cat: "eat",
    area: "Pigalle & Rue des Martyrs",
    address: "22 Boulevard de Clichy, 75018 Paris",
    lat: 48.8826,
    lng: 2.3387,
    price: "€20–30 per person",
    order: ["Boeuf bourguignon"],
    notes: "Big, lively and cheap French classics near Pigalle.",
    price: "€20–30 per person",
    status: "want",
    tags: ["french classics", "cheap"],
  },
  {
    id: "train-bleu",
    name: "Le Train Bleu",
    cat: "eat",
    area: "Bastille & Gare de Lyon",
    address: "Place Louis-Armand, Gare de Lyon, 75012 Paris",
    lat: 48.8447,
    lng: 2.3734,
    price: "€70–100 per person",
    notes: "Belle Époque restaurant inside Gare de Lyon, with gilded painted ceilings. Worth it for the room. Book ahead.",
    hours: "Every day 11:15 – 14:30, 19:00 – 22:30",
    hoursSource: "osm",
    openOn: {"mon": "11:15-14:30,19:00-22:30", "tue": "11:15-14:30,19:00-22:30", "wed": "11:15-14:30,19:00-22:30", "thu": "11:15-14:30,19:00-22:30", "fri": "11:15-14:30,19:00-22:30", "sat": "11:15-14:30,19:00-22:30", "sun": "11:15-14:30,19:00-22:30"},
    price: "€70–100 per person",
    status: "want",
    tags: ["french classics", "instagram"],
  },
  {
    id: "breizh-cafe",
    name: "Breizh Café",
    cat: "eat",
    area: "Le Marais",
    address: "109 Rue Vieille du Temple, 75003 Paris",
    lat: 48.8605,
    lng: 2.3631,
    price: "€20–30 per person",
    order: ["Buckwheat galette", "Salted butter caramel crêpe"],
    drinks: ["Breton cider"],
    notes: "The best-known crêperie in Paris.",
    hours: "Mon–Fri 11:30 – 23:00 · Sat 10:00 – 23:00 · Sun 10:00 – 22:00",
    hoursSource: "osm",
    openOn: {"mon": "11:30-23:00", "tue": "11:30-23:00", "wed": "11:30-23:00", "thu": "11:30-23:00", "fri": "11:30-23:00", "sat": "10:00-23:00", "sun": "10:00-22:00"},
    price: "€20–30 per person",
    status: "want",
    tags: ["crêpes"],
  },
  {
    id: "as-du-fallafel",
    name: "L'As du Fallafel",
    cat: "eat",
    area: "Le Marais",
    address: "34 Rue des Rosiers, 75004 Paris",
    lat: 48.8574,
    lng: 2.3591,
    price: "€10–15 per person",
    order: ["Falafel pita"],
    notes: "Famous falafel pita in the old Jewish quarter. Takeaway window or seats inside.",
    hours: "Mon–Thu 11:00 – midnight · Fri 11:00 – 17:00 · Sat closed · Sun 11:00 – midnight",
    hoursSource: "osm",
    openOn: {"mon": "11:00-24:00", "tue": "11:00-24:00", "wed": "11:00-24:00", "thu": "11:00-24:00", "fri": "11:00-17:00", "sun": "11:00-24:00"},
    closed: ["sat"],
    price: "€10–15 per person",
    status: "want",
    tags: ["cheap"],
  },
  {
    id: "pink-mamma",
    name: "Pink Mamma",
    cat: "eat",
    area: "Pigalle & Rue des Martyrs",
    address: "20 bis Rue de Douai, 75009 Paris",
    lat: 48.8818,
    lng: 2.3329,
    price: "€30–45 per person",
    order: ["Truffle pasta"],
    notes: "Italian restaurant over four floors with a plant-filled glass-roofed top floor. Very Instagrammable.",
    price: "€30–45 per person",
    status: "want",
    tags: ["instagram"],
  },
  {
    id: "higuma",
    name: "Higuma",
    cat: "eat",
    area: "Little Tokyo",
    address: "32 bis Rue Sainte-Anne, 75001 Paris",
    lat: 48.8667,
    lng: 2.3355,
    price: "€12–18 per person",
    order: ["Ramen", "Gyoza"],
    notes: "Busy, cheap ramen counter. A Rue Sainte-Anne classic.",
    hours: "Every day 11:30 – 22:00",
    hoursSource: "osm",
    openOn: {"mon": "11:30-22:00", "tue": "11:30-22:00", "wed": "11:30-22:00", "thu": "11:30-22:00", "fri": "11:30-22:00", "sat": "11:30-22:00", "sun": "11:30-22:00"},
    price: "€12–18 per person",
    status: "want",
    tags: ["japanese", "cheap"],
  },
  {
    id: "kunitoraya",
    name: "Kunitoraya",
    cat: "eat",
    area: "Little Tokyo",
    address: "5 Rue Villedo, 75001 Paris",
    lat: 48.866,
    lng: 2.3355,
    price: "€20–30 per person",
    order: ["Udon"],
    notes: "Handmade udon. There's almost always a queue.",
    price: "€20–30 per person",
    status: "want",
    tags: ["japanese"],
  },
  {
    id: "sanukiya",
    name: "Sanukiya",
    cat: "eat",
    area: "Little Tokyo",
    address: "9 Rue d'Argenteuil, 75001 Paris",
    lat: 48.8652,
    lng: 2.3337,
    price: "€15–22 per person",
    order: ["Udon"],
    notes: "Hand-pulled udon, hot or cold. Long lines at peak hours.",
    hours: "Every day 11:30 – 22:30",
    hoursSource: "osm",
    openOn: {"mon": "11:30-22:30", "tue": "11:30-22:30", "wed": "11:30-22:30", "thu": "11:30-22:30", "fri": "11:30-22:30", "sat": "11:30-22:30", "sun": "11:30-22:30"},
    price: "€15–22 per person",
    status: "want",
    tags: ["japanese", "cheap"],
  },
  {
    id: "dosanko-larmen",
    name: "Dosanko Larmen",
    cat: "eat",
    area: "Little Tokyo",
    address: "40 Rue Sainte-Anne, 75002 Paris",
    lat: 48.8676,
    lng: 2.3356,
    price: "€15–20 per person",
    order: ["Ramen", "Gyoza"],
    notes: "Small place with huge ramen bowls and great gyoza.",
    hours: "Mon–Fri 12:00 – 15:00, 17:00 – 22:30 · Sat–Sun 12:00 – 15:30, 18:00 – 22:30",
    hoursSource: "osm",
    openOn: {"mon": "12:00-15:00,17:00-22:30", "tue": "12:00-15:00,17:00-22:30", "wed": "12:00-15:00,17:00-22:30", "thu": "12:00-15:00,17:00-22:30", "fri": "12:00-15:00,17:00-22:30", "sat": "12:00-15:30,18:00-22:30", "sun": "12:00-15:30,18:00-22:30"},
    price: "€15–20 per person",
    status: "want",
    tags: ["japanese", "cheap"],
  },
  {
    id: "pho-14",
    name: "Pho 14",
    cat: "eat",
    area: "Chinatown",
    address: "129 Avenue de Choisy, 75013 Paris",
    lat: 48.8254,
    lng: 2.3609,
    price: "€12–18 per person",
    order: ["Pho"],
    notes: "Popular Vietnamese pho in Chinatown. Quick and cheap.",
    price: "€12–18 per person",
    status: "want",
    tags: ["asian", "cheap"],
  },
  {
    id: "dong-huong",
    name: "Dong Huong",
    cat: "eat",
    area: "Belleville",
    address: "14 Rue Louis Bonnet, 75011 Paris",
    lat: 48.8709,
    lng: 2.3786,
    price: "€12–18 per person",
    order: ["Pho", "Bò bún"],
    notes: "Long-running Vietnamese restaurant in Belleville.",
    price: "€12–18 per person",
    status: "want",
    tags: ["asian", "cheap"],
  },

  // ── Drink ──
  {
    id: "little-red-door",
    name: "Little Red Door",
    cat: "drink",
    area: "Le Marais",
    address: "60 Rue Charlot, 75003 Paris",
    lat: 48.8634,
    lng: 2.363,
    price: "€16–18 per cocktail",
    notes: "Regularly listed among the world's best cocktail bars. Look for the small red door. Arrive early or expect a wait.",
    hours: "Every day 17:00 – 01:00",
    hoursSource: "osm",
    openOn: {"mon": "17:00-01:00", "tue": "17:00-01:00", "wed": "17:00-01:00", "thu": "17:00-01:00", "fri": "17:00-01:00", "sat": "17:00-01:00", "sun": "17:00-01:00"},
    price: "€16–18 per cocktail",
    status: "want",
    tags: ["cocktails"],
  },
  {
    id: "le-syndicat",
    name: "Le Syndicat",
    cat: "drink",
    area: "Grands Boulevards",
    address: "51 Rue du Faubourg Saint-Denis, 75010 Paris",
    lat: 48.8717,
    lng: 2.3537,
    price: "€14–16 per cocktail",
    notes: "Cocktails made only with French spirits, behind a poster-covered front.",
    price: "€14–16 per cocktail",
    status: "want",
    tags: ["cocktails"],
  },
  {
    id: "candelaria",
    name: "Candelaria",
    cat: "drink",
    area: "Le Marais",
    address: "52 Rue de Saintonge, 75003 Paris",
    lat: 48.8633,
    lng: 2.3637,
    price: "€14–16 per cocktail",
    notes: "Hidden cocktail bar through a door at the back of a small taqueria.",
    hours: "Mon–Wed 12:30 – 23:00 · Thu–Sat 12:30 – midnight · Sun 12:30 – 23:00",
    hoursSource: "osm",
    openOn: {"sun": "12:30-23:00", "mon": "12:30-23:00", "tue": "12:30-23:00", "wed": "12:30-23:00", "thu": "12:30-24:00", "fri": "12:30-24:00", "sat": "12:30-24:00"},
    price: "€14–16 per cocktail",
    status: "want",
    tags: ["cocktails"],
  },
  {
    id: "danico",
    name: "Danico",
    cat: "drink",
    area: "Louvre & Tuileries",
    address: "6 Rue Vivienne, 75002 Paris",
    lat: 48.8667,
    lng: 2.3388,
    price: "€16–18 per cocktail",
    notes: "Cocktail bar at the back of the Daroco restaurant, next to Galerie Vivienne.",
    hours: "Every day 17:00 – 02:00",
    hoursSource: "osm",
    openOn: {"mon": "17:00-02:00", "tue": "17:00-02:00", "wed": "17:00-02:00", "thu": "17:00-02:00", "fri": "17:00-02:00", "sat": "17:00-02:00", "sun": "17:00-02:00"},
    price: "€16–18 per cocktail",
    status: "want",
    tags: ["cocktails"],
  },
  {
    id: "bar-hemingway",
    name: "Bar Hemingway",
    cat: "drink",
    area: "Opéra",
    address: "15 Place Vendôme, 75001 Paris",
    lat: 48.868,
    lng: 2.329,
    price: "€30–40 per cocktail",
    notes: "Small wood-panelled bar inside the Ritz. Classic and expensive. Dress smart.",
    price: "€30–40 per cocktail",
    status: "want",
    tags: ["cocktails", "classic"],
  },
  {
    id: "harrys-bar",
    name: "Harry's New York Bar",
    cat: "drink",
    area: "Opéra",
    address: "5 Rue Daunou, 75002 Paris",
    lat: 48.8697,
    lng: 2.3315,
    price: "€15–20 per cocktail",
    drinks: ["Bloody Mary"],
    notes: "Historic bar where the Bloody Mary is said to have been invented.",
    hours: "Mon–Sat 12:00 – 02:00 · Sun 17:00 – 01:00",
    hoursSource: "osm",
    openOn: {"mon": "12:00-02:00", "tue": "12:00-02:00", "wed": "12:00-02:00", "thu": "12:00-02:00", "fri": "12:00-02:00", "sat": "12:00-02:00", "sun": "17:00-01:00"},
    price: "€15–20 per cocktail",
    status: "want",
    tags: ["cocktails", "classic"],
  },
  {
    id: "le-perchoir",
    name: "Le Perchoir Ménilmontant",
    cat: "drink",
    area: "Belleville",
    address: "14 Rue Crespin du Gast, 75011 Paris",
    lat: 48.8667,
    lng: 2.3824,
    price: "€14–18 per cocktail",
    notes: "The rooftop bar that started the Paris trend, with views towards Sacré-Cœur. Rooftops can close in bad weather, so check before going.",
    bestTime: "Sunset",
    price: "€14–18 per cocktail",
    status: "want",
    tags: ["rooftop", "view", "cocktails", "instagram"],
  },
  {
    id: "les-ombres",
    name: "Les Ombres",
    cat: "drink",
    area: "Eiffel Tower & Trocadéro",
    address: "27 Quai Branly, 75007 Paris",
    lat: 48.861,
    lng: 2.2975,
    price: "€18–22 per cocktail",
    notes: "Rooftop restaurant and bar on the Musée du quai Branly, directly facing the Eiffel Tower. Book for dinner.",
    bestTime: "After dark, when the tower sparkles on the hour",
    hours: "Every day 12:00 – 23:00",
    hoursSource: "osm",
    openOn: {"mon": "12:00-23:00", "tue": "12:00-23:00", "wed": "12:00-23:00", "thu": "12:00-23:00", "fri": "12:00-23:00", "sat": "12:00-23:00", "sun": "12:00-23:00"},
    bookAhead: "Book a table if you want dinner. Drinks at the bar may not need a booking.",
    price: "€18–22 per cocktail",
    status: "want",
    tags: ["rooftop", "view", "instagram", "to book"],
  },
  {
    id: "terrass-hotel",
    name: "Terrass'' Hôtel rooftop",
    cat: "drink",
    area: "Montmartre",
    address: "12 Rue Joseph de Maistre, 75018 Paris",
    lat: 48.8866,
    lng: 2.3326,
    price: "€16–20 per cocktail",
    notes: "Rooftop bar on top of a Montmartre hotel with a view over Paris to the Eiffel Tower.",
    bestTime: "Sunset",
    price: "€16–20 per cocktail",
    status: "want",
    tags: ["rooftop", "view", "cocktails"],
  },
  {
    id: "baron-rouge",
    name: "Le Baron Rouge",
    cat: "drink",
    area: "Bastille & Gare de Lyon",
    address: "1 Rue Théophile Roussel, 75012 Paris",
    lat: 48.8494,
    lng: 2.3779,
    price: "€4–7 per glass of wine",
    notes: "Lively, old-school wine bar by the Marché d'Aligre. Wine straight from the barrel.",
    hours: "Mon 17:00 – 22:00 · Tue–Fri 10:00 – 14:00, 17:00 – 22:00 · Sat 10:00 – 22:00 · Sun 10:00 – 16:00",
    hoursSource: "osm",
    openOn: {"mon": "17:00-22:00", "tue": "10:00-14:00,17:00-22:00", "wed": "10:00-14:00,17:00-22:00", "thu": "10:00-14:00,17:00-22:00", "fri": "10:00-14:00,17:00-22:00", "sat": "10:00-22:00", "sun": "10:00-16:00"},
    price: "€4–7 per glass of wine",
    status: "want",
    tags: ["wine", "cheap"],
  },
  {
    id: "frenchie-bar-a-vins",
    name: "Frenchie Bar à Vins",
    cat: "drink",
    area: "Montorgueil & Les Halles",
    address: "6 Rue du Nil, 75002 Paris",
    lat: 48.8677,
    lng: 2.3478,
    price: "€8–14 per glass of wine",
    notes: "Wine bar with excellent small plates. No reservations, so go early.",
    price: "€8–14 per glass of wine",
    status: "want",
    tags: ["wine"],
  },

  // ── Cafés ──
  {
    id: "cafe-de-flore",
    name: "Café de Flore",
    cat: "cafe",
    area: "Saint-Germain",
    address: "172 Boulevard Saint-Germain, 75006 Paris",
    lat: 48.8541,
    lng: 2.3325,
    price: "€10–18 per person",
    drinks: ["Hot chocolate", "Café crème"],
    notes: "Classic Paris café since the 1880s. The photo is under the white awning outside.",
    hours: "Every day 07:30 – 01:30",
    hoursSource: "osm",
    openOn: {"mon": "07:30-01:30", "tue": "07:30-01:30", "wed": "07:30-01:30", "thu": "07:30-01:30", "fri": "07:30-01:30", "sat": "07:30-01:30", "sun": "07:30-01:30"},
    price: "€10–18 per person",
    status: "want",
    tags: ["classic", "instagram", "terrace", "hot chocolate"],
  },
  {
    id: "deux-magots",
    name: "Les Deux Magots",
    cat: "cafe",
    area: "Saint-Germain",
    address: "6 Place Saint-Germain-des-Prés, 75006 Paris",
    lat: 48.854,
    lng: 2.3333,
    price: "€10–18 per person",
    drinks: ["Hot chocolate"],
    notes: "Famous literary café next door to Café de Flore. Terrace facing the church.",
    hours: "Every day 07:30 – 01:00",
    hoursSource: "osm",
    openOn: {"mon": "07:30-01:00", "tue": "07:30-01:00", "wed": "07:30-01:00", "thu": "07:30-01:00", "fri": "07:30-01:00", "sat": "07:30-01:00", "sun": "07:30-01:00"},
    price: "€10–18 per person",
    status: "want",
    tags: ["classic", "terrace", "hot chocolate"],
  },
  {
    id: "maison-rose",
    name: "La Maison Rose",
    cat: "cafe",
    area: "Montmartre",
    address: "2 Rue de l'Abreuvoir, 75018 Paris",
    lat: 48.8874,
    lng: 2.3397,
    price: "€15–25 per person",
    notes: "The pink house. The most photographed café front in Paris.",
    bestTime: "Before 9:00, for the photo without crowds",
    hours: "Every day 11:00 – 22:30",
    hoursSource: "osm",
    openOn: {"mon": "11:00-22:30", "tue": "11:00-22:30", "wed": "11:00-22:30", "thu": "11:00-22:30", "fri": "11:00-22:30", "sat": "11:00-22:30", "sun": "11:00-22:30"},
    price: "€15–25 per person",
    status: "want",
    tags: ["instagram"],
  },
  {
    id: "le-consulat",
    name: "Le Consulat",
    cat: "cafe",
    area: "Montmartre",
    address: "18 Rue Norvins, 75018 Paris",
    lat: 48.8864,
    lng: 2.3399,
    price: "€15–25 per person",
    notes: "Picture-postcard corner café near Place du Tertre.",
    price: "€15–25 per person",
    status: "want",
    tags: ["instagram", "classic", "terrace"],
  },
  {
    id: "deux-moulins",
    name: "Café des Deux Moulins",
    cat: "cafe",
    area: "Montmartre",
    address: "15 Rue Lepic, 75018 Paris",
    lat: 48.8847,
    lng: 2.3337,
    price: "€15–25 per person",
    order: ["Crème brûlée"],
    notes: "The café from the film Amélie.",
    hours: "Mon–Fri 07:30 – 02:00 · Sat–Sun 08:00 – 02:00",
    hoursSource: "osm",
    openOn: {"mon": "07:30-02:00", "tue": "07:30-02:00", "wed": "07:30-02:00", "thu": "07:30-02:00", "fri": "07:30-02:00", "sat": "08:00-02:00", "sun": "08:00-02:00"},
    price: "€15–25 per person",
    status: "want",
    tags: ["film"],
  },
  {
    id: "angelina",
    name: "Angelina Rivoli",
    cat: "cafe",
    area: "Louvre & Tuileries",
    address: "226 Rue de Rivoli, 75001 Paris",
    lat: 48.865,
    lng: 2.3284,
    price: "€15–25 per person",
    order: ["Mont-Blanc"],
    drinks: ["L'Africain hot chocolate"],
    notes: "Belle Époque tea room. Famous for thick hot chocolate and the Mont-Blanc. Expect a queue.",
    hours: "Mon–Thu 07:30 – 19:00 · Fri 07:30 – 19:30 · Sat–Sun 08:00 – 19:30",
    hoursSource: "osm",
    openOn: {"mon": "07:30-19:00", "tue": "07:30-19:00", "wed": "07:30-19:00", "thu": "07:30-19:00", "fri": "07:30-19:30", "sat": "08:00-19:30", "sun": "08:00-19:30"},
    price: "€15–25 per person",
    status: "want",
    tags: ["hot chocolate", "pastry", "instagram", "rainy"],
  },
  {
    id: "kitsune-palais-royal",
    name: "Café Kitsuné Palais Royal",
    cat: "cafe",
    area: "Louvre & Tuileries",
    address: "51 Galerie de Montpensier, 75001 Paris",
    lat: 48.8653,
    lng: 2.3373,
    price: "€5–10 per person",
    drinks: ["Matcha latte", "Coffee"],
    notes: "Small coffee bar inside the Palais-Royal gardens. Fox-shaped biscuits.",
    hours: "Mon–Sat 9:00–18:30, Sun 10:00–18:30",
    open: "09:00-18:30",
    openOn: {"sun": "10:00-18:30"},
    price: "€5–10 per person",
    status: "want",
    tags: ["matcha", "coffee", "instagram"],
  },
  {
    id: "cafe-marly",
    name: "Le Café Marly",
    cat: "cafe",
    area: "Louvre & Tuileries",
    address: "93 Rue de Rivoli, 75001 Paris",
    lat: 48.8617,
    lng: 2.3357,
    price: "€20–40 per person",
    notes: "Terrace under the Louvre arcades looking straight at the glass pyramid.",
    hours: "Every day 08:00 – 02:00",
    hoursSource: "osm",
    openOn: {"mon": "08:00-02:00", "tue": "08:00-02:00", "wed": "08:00-02:00", "thu": "08:00-02:00", "fri": "08:00-02:00", "sat": "08:00-02:00", "sun": "08:00-02:00"},
    price: "€20–40 per person",
    status: "want",
    tags: ["view", "terrace", "instagram"],
  },
  {
    id: "boot-cafe",
    name: "Boot Café",
    cat: "cafe",
    area: "Le Marais",
    address: "19 Rue du Pont aux Choux, 75003 Paris",
    lat: 48.8606,
    lng: 2.3654,
    price: "€5–10 per person",
    drinks: ["Coffee", "Matcha"],
    notes: "Tiny coffee shop in a former cobbler's shop, with a blue shopfront.",
    hours: "Every day 10:00 – 18:00",
    hoursSource: "osm",
    openOn: {"mon": "10:00-18:00", "tue": "10:00-18:00", "wed": "10:00-18:00", "thu": "10:00-18:00", "fri": "10:00-18:00", "sat": "10:00-18:00", "sun": "10:00-18:00"},
    price: "€5–10 per person",
    status: "want",
    tags: ["coffee", "matcha", "instagram"],
  },
  {
    id: "ob-la-di",
    name: "Ob-La-Di",
    cat: "cafe",
    area: "Le Marais",
    address: "54 Rue de Saintonge, 75003 Paris",
    lat: 48.8635,
    lng: 2.3637,
    price: "€8–15 per person",
    drinks: ["Matcha latte"],
    notes: "Small, bright café. Popular for matcha and brunch.",
    price: "€8–15 per person",
    status: "want",
    tags: ["matcha", "coffee"],
  },
  {
    id: "cafeotheque",
    name: "La Caféothèque",
    cat: "cafe",
    area: "Le Marais",
    address: "52 Rue de l'Hôtel de Ville, 75004 Paris",
    lat: 48.8549,
    lng: 2.3567,
    price: "€4–8 per person",
    notes: "Specialty coffee roaster by the Seine.",
    hours: "Every day 09:30 – 19:00",
    hoursSource: "osm",
    openOn: {"mon": "09:30-19:00", "tue": "09:30-19:00", "wed": "09:30-19:00", "thu": "09:30-19:00", "fri": "09:30-19:00", "sat": "09:30-19:00", "sun": "09:30-19:00"},
    price: "€4–8 per person",
    status: "want",
    tags: ["coffee"],
  },
  {
    id: "shakespeare-cafe",
    name: "Shakespeare and Company Café",
    cat: "cafe",
    area: "Latin Quarter",
    address: "37 Rue de la Bûcherie, 75005 Paris",
    lat: 48.8526,
    lng: 2.3471,
    price: "€5–10 per person",
    notes: "Café beside the famous English bookshop, facing Notre-Dame.",
    hours: "Every day 10:00 – 23:00",
    hoursSource: "osm",
    openOn: {"mon": "10:00-23:00", "tue": "10:00-23:00", "wed": "10:00-23:00", "thu": "10:00-23:00", "fri": "10:00-23:00", "sat": "10:00-23:00", "sun": "10:00-23:00"},
    price: "€5–10 per person",
    status: "want",
    tags: ["coffee", "books"],
  },
  {
    id: "carette",
    name: "Carette Trocadéro",
    cat: "cafe",
    area: "Eiffel Tower & Trocadéro",
    address: "4 Place du Trocadéro et du 11 Novembre, 75016 Paris",
    lat: 48.8633,
    lng: 2.2872,
    price: "€15–25 per person",
    order: ["Macarons"],
    notes: "Classic tea room near the Trocadéro. Good stop before Eiffel Tower photos.",
    hours: "Every day 07:30 – midnight",
    hoursSource: "osm",
    openOn: {"mon": "07:30-24:00", "tue": "07:30-24:00", "wed": "07:30-24:00", "thu": "07:30-24:00", "fri": "07:30-24:00", "sat": "07:30-24:00", "sun": "07:30-24:00"},
    price: "€15–25 per person",
    status: "want",
    tags: ["pastry", "macarons", "terrace"],
  },
  {
    id: "laduree-champs",
    name: "Ladurée Champs-Élysées",
    cat: "cafe",
    area: "Champs-Élysées",
    address: "75 Avenue des Champs-Élysées, 75008 Paris",
    lat: 48.8711,
    lng: 2.3031,
    price: "€15–30 per person",
    order: ["Macarons"],
    notes: "The famous macaron house in its grand tea-room setting.",
    hours: "Every day 08:00 – 22:00",
    hoursSource: "osm",
    openOn: {"mon": "08:00-22:00", "tue": "08:00-22:00", "wed": "08:00-22:00", "thu": "08:00-22:00", "fri": "08:00-22:00", "sat": "08:00-22:00", "sun": "08:00-22:00"},
    price: "€15–30 per person",
    status: "want",
    tags: ["macarons", "instagram", "rainy"],
  },

  // ── Pastry ──
  {
    id: "pierre-herme-bonaparte",
    name: "Pierre Hermé",
    cat: "pastry",
    area: "Saint-Germain",
    address: "72 Rue Bonaparte, 75006 Paris",
    lat: 48.8516,
    lng: 2.3326,
    price: "€2.50–3.50 per macaron · €8–10 per pastry",
    order: ["Ispahan (rose, lychee, raspberry)", "Macarons: Ispahan, Mogador, Mosaïc"],
    notes: "Ranked best pâtisserie in the world by La Liste 2026. Takeaway shop.",
    hours: "Mon–Sat 10:00 – 20:00 · Sun 10:00 – 19:00",
    hoursSource: "osm",
    openOn: {"mon": "10:00-20:00", "tue": "10:00-20:00", "wed": "10:00-20:00", "thu": "10:00-20:00", "fri": "10:00-20:00", "sat": "10:00-20:00", "sun": "10:00-19:00"},
    price: "€2.50–3.50 per macaron · €8–10 per pastry",
    status: "want",
    tags: ["macarons", "top pick"],
  },
  {
    id: "laduree-royale",
    name: "Ladurée Royale",
    cat: "pastry",
    area: "Opéra",
    address: "16 Rue Royale, 75008 Paris",
    lat: 48.8697,
    lng: 2.3226,
    price: "€2.50–3.50 per macaron · €8–10 per pastry",
    order: ["Macarons: salted caramel, pistachio", "Ispahan"],
    notes: "The original Ladurée shop and tea room. The prettiest pastel macarons and boxes.",
    price: "€2.50–3.50 per macaron · €8–10 per pastry",
    status: "want",
    tags: ["macarons", "instagram", "tea room", "rainy"],
  },
  {
    id: "carette-vosges",
    name: "Carette Place des Vosges",
    cat: "pastry",
    area: "Le Marais",
    address: "25 Place des Vosges, 75003 Paris",
    lat: 48.8559,
    lng: 2.3659,
    price: "€2.50–3.50 per macaron · €15–25 sitting down",
    order: ["Macarons", "Millefeuille"],
    notes: "Tea room under the arcades of Place des Vosges. Some say the best macarons in Paris, with a crunchier bite.",
    price: "€2.50–3.50 per macaron · €15–25 sitting down",
    status: "want",
    tags: ["macarons", "tea room", "terrace"],
  },
  {
    id: "dalloyau",
    name: "Dalloyau",
    cat: "pastry",
    area: "Champs-Élysées",
    address: "101 Rue du Faubourg Saint-Honoré, 75008 Paris",
    lat: 48.8726,
    lng: 2.3112,
    price: "€2.50–3.50 per macaron · €7–10 per cake",
    order: ["Opéra cake", "Macarons"],
    notes: "Historic pastry house dating back to 1682. Home of the Opéra cake.",
    price: "€2.50–3.50 per macaron · €7–10 per cake",
    status: "want",
    tags: ["macarons", "historic"],
  },
  {
    id: "stohrer",
    name: "Stohrer",
    cat: "pastry",
    area: "Montorgueil & Les Halles",
    address: "51 Rue Montorgueil, 75002 Paris",
    lat: 48.8649,
    lng: 2.347,
    price: "€5–8 per pastry",
    order: ["Baba au rhum", "Puits d'amour", "Éclairs"],
    notes: "The oldest pâtisserie in Paris, founded in 1730. The baba au rhum was created here. Beautiful painted interior.",
    hours: "Mon–Fri 08:00 – 20:30 · Sun 08:00 – 20:00",
    hoursSource: "osm",
    openOn: {"mon": "08:00-20:30", "tue": "08:00-20:30", "wed": "08:00-20:30", "thu": "08:00-20:30", "fri": "08:00-20:30", "sun": "08:00-20:00"},
    price: "€5–8 per pastry",
    status: "want",
    tags: ["baba au rhum", "éclairs", "historic", "instagram"],
  },
  {
    id: "fou-de-patisserie",
    name: "Fou de Pâtisserie",
    cat: "pastry",
    area: "Montorgueil & Les Halles",
    address: "45 Rue Montorgueil, 75002 Paris",
    lat: 48.8646,
    lng: 2.347,
    price: "€6–12 per pastry",
    order: ["Pastries from top Paris chefs"],
    notes: "One shop selling pastries from many of the city's best chefs. Good for trying several in one stop.",
    price: "€6–12 per pastry",
    status: "want",
    tags: ["fruit pastries", "éclairs", "millefeuille"],
  },
  {
    id: "cedric-grolet-opera",
    name: "Cédric Grolet Opéra",
    cat: "pastry",
    area: "Opéra",
    address: "35 Avenue de l'Opéra, 75002 Paris",
    lat: 48.868,
    lng: 2.3333,
    price: "€15–20 per pastry",
    order: ["Trompe-l'œil fruit pastries", "Croissant"],
    notes: "Pastries that look exactly like real fruit. Very Instagrammable. Expect a queue.",
    hours: "Wed–Sun 08:30 – 18:00",
    hoursSource: "osm",
    openOn: {"wed": "08:30-18:00", "thu": "08:30-18:00", "fri": "08:30-18:00", "sat": "08:30-18:00", "sun": "08:30-18:00"},
    price: "€15–20 per pastry",
    status: "want",
    tags: ["fruit pastries", "croissants", "instagram", "top pick"],
  },
  {
    id: "ritz-comptoir",
    name: "Ritz Paris Le Comptoir",
    cat: "pastry",
    area: "Opéra",
    address: "38 Rue Cambon, 75001 Paris",
    lat: 48.8681,
    lng: 2.3285,
    price: "€4–8 per item",
    order: ["Madeleines", "Marbled cake"],
    notes: "Small pastry counter of the Ritz hotel, at the back on Rue Cambon. Known for its madeleines.",
    price: "€4–8 per item",
    status: "want",
    tags: ["madeleines", "luxury"],
  },
  {
    id: "eclair-de-genie",
    name: "L'Éclair de Génie",
    cat: "pastry",
    area: "Le Marais",
    address: "14 Rue Pavée, 75004 Paris",
    lat: 48.8559,
    lng: 2.3608,
    price: "€6–9 per éclair",
    order: ["Éclairs"],
    notes: "Rows of colourful éclairs in many flavours.",
    price: "€6–9 per éclair",
    status: "want",
    tags: ["éclairs", "instagram"],
  },
  {
    id: "jacques-genin",
    name: "Jacques Genin",
    cat: "pastry",
    area: "Le Marais",
    address: "133 Rue de Turenne, 75003 Paris",
    lat: 48.8628,
    lng: 2.3647,
    price: "€10–15 for the millefeuille",
    order: ["Millefeuille, made to order", "Caramels"],
    notes: "Chocolatier famous for a millefeuille assembled when you order it, plus soft caramels.",
    price: "€10–15 for the millefeuille",
    status: "want",
    tags: ["millefeuille", "chocolate", "caramels"],
  },
  {
    id: "sebastien-gaudard",
    name: "Sébastien Gaudard",
    cat: "pastry",
    area: "Pigalle & Rue des Martyrs",
    address: "22 Rue des Martyrs, 75009 Paris",
    lat: 48.8786,
    lng: 2.3394,
    price: "€6–9 per pastry",
    order: ["Paris-Brest", "Millefeuille"],
    notes: "Classic French pastries done perfectly, in a pretty old-style shop.",
    price: "€6–9 per pastry",
    status: "want",
    tags: ["millefeuille", "choux", "classic"],
  },
  {
    id: "mamiche",
    name: "Mamiche",
    cat: "pastry",
    area: "Pigalle & Rue des Martyrs",
    address: "45 Rue Condorcet, 75009 Paris",
    lat: 48.88,
    lng: 2.3446,
    price: "€3–6 per item",
    order: ["Babka", "Cream puffs"],
    notes: "Popular neighbourhood bakery. Known for chocolate babka and cream puffs.",
    hours: "Mon–Fri 08:00 – 20:00 · Sat 08:00 – 19:00",
    hoursSource: "osm",
    openOn: {"mon": "08:00-20:00", "tue": "08:00-20:00", "wed": "08:00-20:00", "thu": "08:00-20:00", "fri": "08:00-20:00", "sat": "08:00-19:00"},
    price: "€3–6 per item",
    status: "want",
    tags: ["choux", "viennoiserie"],
  },
  {
    id: "odette",
    name: "Odette",
    cat: "pastry",
    area: "Latin Quarter",
    address: "77 Rue Galande, 75005 Paris",
    lat: 48.8523,
    lng: 2.3469,
    price: "€2–4 per cream puff",
    order: ["Choux cream puffs"],
    notes: "Cream puffs in a little green-and-white house across the river from Notre-Dame.",
    hours: "Mon 11:00 – 19:00 · Tue–Wed 12:00 – 19:00 · Thu–Fri 11:00 – 19:00 · Sat–Sun 11:00 – 20:00",
    hoursSource: "osm",
    openOn: {"mon": "11:00-19:00", "thu": "11:00-19:00", "fri": "11:00-19:00", "sat": "11:00-20:00", "sun": "11:00-20:00", "tue": "12:00-19:00", "wed": "12:00-19:00"},
    price: "€2–4 per cream puff",
    status: "want",
    tags: ["choux", "instagram"],
  },
  {
    id: "aki-boulangerie",
    name: "Aki Boulangerie",
    cat: "pastry",
    area: "Little Tokyo",
    address: "16 Rue Sainte-Anne, 75001 Paris",
    lat: 48.8659,
    lng: 2.3357,
    price: "€3–8 per item",
    order: ["Matcha pastries", "Melon pan", "Onigiri"],
    notes: "Japanese-French bakery on Rue Sainte-Anne. Matcha viennoiseries and bento lunches.",
    price: "€3–8 per item",
    status: "want",
    tags: ["japanese", "matcha", "viennoiserie"],
  },
  {
    id: "du-pain-et-des-idees",
    name: "Du Pain et des Idées",
    cat: "pastry",
    area: "Canal Saint-Martin",
    address: "34 Rue Yves Toudic, 75010 Paris",
    lat: 48.8706,
    lng: 2.3628,
    price: "€4–6 per pastry",
    order: ["Pistachio-chocolate escargot", "Pain des amis"],
    notes: "Bakery known for the pistachio-chocolate escargot pastry. Takeaway only.",
    hours: "Closed weekends",
    closed: ["sat", "sun"],
    price: "€4–6 per pastry",
    status: "want",
    tags: ["viennoiserie", "croissants", "top pick"],
  },
  {
    id: "la-parisienne",
    name: "La Parisienne",
    cat: "pastry",
    area: "Grands Boulevards",
    address: "12 Rue du Faubourg Poissonnière, 75010 Paris",
    lat: 48.8714,
    lng: 2.3484,
    price: "€1.50–2.50 per croissant",
    order: ["Butter croissant", "Pain au chocolat"],
    notes: "2nd place, Best Butter Croissant of Greater Paris 2025.",
    hours: "Mon–Sat 07:00 – 20:00 · Sun 07:00 – 14:30",
    hoursSource: "osm",
    openOn: {"mon": "07:00-20:00", "tue": "07:00-20:00", "wed": "07:00-20:00", "thu": "07:00-20:00", "fri": "07:00-20:00", "sat": "07:00-20:00", "sun": "07:00-14:30"},
    price: "€1.50–2.50 per croissant",
    status: "want",
    tags: ["croissants", "pain au chocolat", "award"],
  },
  {
    id: "mille-et-un",
    name: "Boulangerie Mille et Un",
    cat: "pastry",
    area: "Saint-Germain",
    address: "32 Rue Saint-Placide, 75006 Paris",
    lat: 48.8497,
    lng: 2.3266,
    price: "€1.50–2.50 per croissant",
    order: ["Butter croissant", "Pain au chocolat"],
    notes: "3rd place, Best Butter Croissant of Greater Paris 2025.",
    price: "€1.50–2.50 per croissant",
    status: "want",
    tags: ["croissants", "pain au chocolat", "award"],
  },
  {
    id: "rabineau",
    name: "Boulangerie Moderne Rabineau",
    cat: "pastry",
    area: "Latin Quarter",
    address: "16 Rue des Fossés-Saint-Jacques, 75005 Paris",
    lat: 48.8455,
    lng: 2.3443,
    price: "€1.50–2.50 per croissant",
    order: ["Butter croissant"],
    notes: "4th place, Best Butter Croissant of Greater Paris 2025. Near the Panthéon.",
    hours: "Mon–Fri 07:00 – 20:00 · Sat 08:00 – 15:00",
    hoursSource: "osm",
    openOn: {"mon": "07:00-20:00", "tue": "07:00-20:00", "wed": "07:00-20:00", "thu": "07:00-20:00", "fri": "07:00-20:00", "sat": "08:00-15:00"},
    price: "€1.50–2.50 per croissant",
    status: "want",
    tags: ["croissants", "award"],
  },
  {
    id: "utopie",
    name: "Boulangerie Utopie",
    cat: "pastry",
    area: "Bastille & 11th",
    address: "20 Rue Jean-Pierre Timbaud, 75011 Paris",
    lat: 48.8653,
    lng: 2.3671,
    price: "€1.50–6 per item",
    order: ["Croissant", "Black sesame éclair"],
    notes: "Creative bakery loved for its croissants and unusual flavours.",
    hours: "Tue–Sun 07:00 – 20:00",
    hoursSource: "osm",
    openOn: {"tue": "07:00-20:00", "wed": "07:00-20:00", "thu": "07:00-20:00", "fri": "07:00-20:00", "sat": "07:00-20:00", "sun": "07:00-20:00"},
    price: "€1.50–6 per item",
    status: "want",
    tags: ["croissants", "éclairs", "viennoiserie"],
  },

  // ── Shop ──
  {
    id: "repetto",
    name: "Repetto",
    cat: "shop",
    area: "Opéra",
    address: "22 Rue de la Paix, 75002 Paris",
    lat: 48.8694,
    lng: 2.3312,
    notes: "The original Repetto shop, open since 1959 next to the Opéra. Famous ballet flats, including the 'Cendrillon' made for Brigitte Bardot.",
    status: "want",
    tags: ["shoes", "fashion", "instagram"],
  },
  {
    id: "buly",
    name: "Officine Universelle Buly",
    cat: "shop",
    area: "Saint-Germain",
    address: "6 Rue Bonaparte, 75006 Paris",
    lat: 48.8562,
    lng: 2.3343,
    notes: "Beautiful old-apothecary-style shop. Combs (including Japanese boxwood), brushes, soaps and perfumes. Ask about name calligraphy on your purchase.",
    hours: "Every day 10:00 – 18:00",
    hoursSource: "osm",
    openOn: {"mon": "10:00-18:00", "tue": "10:00-18:00", "wed": "10:00-18:00", "thu": "10:00-18:00", "fri": "10:00-18:00", "sat": "10:00-18:00", "sun": "10:00-18:00"},
    status: "want",
    tags: ["hair", "beauty", "instagram"],
  },
  {
    id: "maison-caillau",
    name: "Maison Caillau",
    cat: "shop",
    area: "Champs-Élysées",
    address: "124 Rue du Faubourg Saint-Honoré, 75008 Paris",
    lat: 48.874,
    lng: 2.3106,
    notes: "French artisan hair accessories: combs, hair clips, headbands and bows.",
    hours: "Mon–Sat 10:00–19:00",
    open: "10:00-19:00",
    closed: ["sun"],
    status: "want",
    tags: ["hair", "fashion"],
  },
  {
    id: "la-bonne-brosse",
    name: "La Bonne Brosse",
    cat: "shop",
    area: "Louvre & Tuileries",
    address: "18 Rue de Richelieu, 75001 Paris",
    lat: 48.864,
    lng: 2.3366,
    notes: "Handmade hairbrushes and combs.",
    hours: "Tue–Sat 11:00 – 19:00",
    hoursSource: "osm",
    openOn: {"tue": "11:00-19:00", "wed": "11:00-19:00", "thu": "11:00-19:00", "fri": "11:00-19:00", "sat": "11:00-19:00"},
    status: "want",
    tags: ["hair", "beauty"],
  },
  {
    id: "alexandre-de-paris",
    name: "Alexandre de Paris",
    cat: "shop",
    area: "Louvre & Tuileries",
    address: "La Samaritaine, 9 Rue de la Monnaie, 75001 Paris",
    lat: 48.859,
    lng: 2.3428,
    notes: "Hair clips, barrettes and combs made in France, inside La Samaritaine.",
    status: "want",
    tags: ["hair", "fashion"],
  },
  {
    id: "samaritaine",
    name: "La Samaritaine",
    cat: "shop",
    area: "Louvre & Tuileries",
    address: "9 Rue de la Monnaie, 75001 Paris",
    lat: 48.8589,
    lng: 2.3424,
    notes: "Art Nouveau department store by the Pont Neuf, with a glass roof and peacock frieze.",
    hours: "Every day 10:00 – 20:00",
    hoursSource: "osm",
    openOn: {"mon": "10:00-20:00", "tue": "10:00-20:00", "wed": "10:00-20:00", "thu": "10:00-20:00", "fri": "10:00-20:00", "sat": "10:00-20:00", "sun": "10:00-20:00"},
    status: "want",
    tags: ["department store", "fashion", "beauty", "instagram", "rainy"],
  },
  {
    id: "bon-marche",
    name: "Le Bon Marché",
    cat: "shop",
    area: "Saint-Germain",
    address: "24 Rue de Sèvres, 75007 Paris",
    lat: 48.851,
    lng: 2.3245,
    notes: "The most elegant department store in Paris. Fashion, beauty and the famous escalators.",
    hours: "Mon–Wed 10:00 – 20:00 · Thu 10:00 – 20:45 · Fri–Sat 10:00 – 20:00 · Sun 11:00 – 20:00",
    hoursSource: "osm",
    openOn: {"mon": "10:00-20:00", "tue": "10:00-20:00", "wed": "10:00-20:00", "fri": "10:00-20:00", "sat": "10:00-20:00", "thu": "10:00-20:45", "sun": "11:00-20:00"},
    status: "want",
    tags: ["department store", "fashion", "beauty", "rainy"],
  },
  {
    id: "grande-epicerie",
    name: "La Grande Épicerie de Paris",
    cat: "shop",
    area: "Saint-Germain",
    address: "38 Rue de Sèvres, 75007 Paris",
    lat: 48.8507,
    lng: 2.3237,
    notes: "Huge luxury food hall next to Le Bon Marché. The best place for food gifts: chocolate, jams, salted butter caramel.",
    hours: "Mon–Sat 08:30 – 21:00 · Sun 10:00 – 20:00",
    hoursSource: "osm",
    openOn: {"mon": "08:30-21:00", "tue": "08:30-21:00", "wed": "08:30-21:00", "thu": "08:30-21:00", "fri": "08:30-21:00", "sat": "08:30-21:00", "sun": "10:00-20:00"},
    status: "want",
    tags: ["food & gifts", "rainy"],
  },
  {
    id: "citypharma",
    name: "Citypharma",
    cat: "shop",
    area: "Saint-Germain",
    address: "26 Rue du Four, 75006 Paris",
    lat: 48.853,
    lng: 2.3335,
    notes: "The famous cheap pharmacy for French skincare (La Roche-Posay, Avène, Caudalie, Nuxe). Very busy, so go early.",
    hours: "Open every day, Sundays until 20:00",
    status: "want",
    tags: ["beauty"],
  },
  {
    id: "diptyque",
    name: "Diptyque",
    cat: "shop",
    area: "Latin Quarter",
    address: "34 Boulevard Saint-Germain, 75005 Paris",
    lat: 48.8497,
    lng: 2.3519,
    notes: "The original Diptyque shop, since 1961. Candles and perfume.",
    hours: "Mon–Sat 10:00 – 19:00",
    hoursSource: "osm",
    openOn: {"mon": "10:00-19:00", "tue": "10:00-19:00", "wed": "10:00-19:00", "thu": "10:00-19:00", "fri": "10:00-19:00", "sat": "10:00-19:00"},
    status: "want",
    tags: ["beauty", "home"],
  },
  {
    id: "merci",
    name: "Merci",
    cat: "shop",
    area: "Le Marais",
    address: "111 Boulevard Beaumarchais, 75003 Paris",
    lat: 48.8604,
    lng: 2.3666,
    notes: "Concept store with fashion, home goods and a café. The red Fiat in the courtyard is the photo.",
    hours: "Mon–Wed 10:30 – 19:30 · Thu–Fri 10:30 – 20:00 · Sat 10:00 – 20:00 · Sun 10:00 – 19:30",
    hoursSource: "osm",
    openOn: {"mon": "10:30-19:30", "tue": "10:30-19:30", "wed": "10:30-19:30", "thu": "10:30-20:00", "fri": "10:30-20:00", "sat": "10:00-20:00", "sun": "10:00-19:30"},
    status: "want",
    tags: ["fashion", "home", "instagram"],
  },
  {
    id: "mariage-freres",
    name: "Mariage Frères",
    cat: "shop",
    area: "Le Marais",
    address: "30 Rue du Bourg-Tibourg, 75004 Paris",
    lat: 48.8578,
    lng: 2.3549,
    notes: "Historic French tea house with a shop and a colonial-style tea room.",
    status: "want",
    tags: ["food & gifts", "tea room"],
  },
  {
    id: "sezane",
    name: "Sézane L'Appartement",
    cat: "shop",
    area: "Grands Boulevards",
    address: "1 Rue Saint-Fiacre, 75002 Paris",
    lat: 48.8702,
    lng: 2.3462,
    notes: "The Paris flagship of the French fashion brand, set up like an apartment.",
    status: "want",
    tags: ["fashion"],
  },
  {
    id: "dehillerin",
    name: "E.Dehillerin",
    cat: "shop",
    area: "Montorgueil & Les Halles",
    address: "18 Rue Coquillière, 75001 Paris",
    lat: 48.8636,
    lng: 2.3433,
    notes: "Old chef's cookware shop, open since 1820. Copper pans and kitchen tools.",
    hours: "Mon 09:00 – 12:30, 14:00 – 18:00 · Tue–Fri 09:00 – 19:00 · Sat 09:00 – 18:00",
    hoursSource: "osm",
    openOn: {"mon": "09:00-12:30,14:00-18:00", "tue": "09:00-19:00", "wed": "09:00-19:00", "thu": "09:00-19:00", "fri": "09:00-19:00", "sat": "09:00-18:00"},
    status: "want",
    tags: ["home"],
  },
  {
    id: "shakespeare-books",
    name: "Shakespeare and Company",
    cat: "shop",
    area: "Latin Quarter",
    address: "37 Rue de la Bûcherie, 75005 Paris",
    lat: 48.8526,
    lng: 2.3471,
    notes: "The famous English-language bookshop facing Notre-Dame.",
    hours: "Every day 10:00 – 23:00",
    hoursSource: "osm",
    openOn: {"mon": "10:00-23:00", "tue": "10:00-23:00", "wed": "10:00-23:00", "thu": "10:00-23:00", "fri": "10:00-23:00", "sat": "10:00-23:00", "sun": "10:00-23:00"},
    status: "want",
    tags: ["books", "instagram", "rainy"],
  },
  {
    id: "enfants-rouges",
    name: "Marché des Enfants Rouges",
    cat: "shop",
    area: "Le Marais",
    address: "39 Rue de Bretagne, 75003 Paris",
    lat: 48.8628,
    lng: 2.3619,
    notes: "The oldest covered market in Paris, with food stalls for lunch.",
    hours: "Mon closed · Tue–Wed 08:30 – 20:30 · Thu 08:30 – 21:30 · Fri–Sat 08:30 – 20:30 · Sun 08:30 – 17:00",
    hoursSource: "osm",
    openOn: {"tue": "08:30-20:30", "wed": "08:30-20:30", "thu": "08:30-21:30", "fri": "08:30-20:30", "sat": "08:30-20:30", "sun": "08:30-17:00"},
    closed: ["mon"],
    status: "want",
    tags: ["markets", "cheap"],
  },
  {
    id: "saint-ouen",
    name: "Marché aux Puces de Saint-Ouen",
    cat: "shop",
    area: "Saint-Ouen (flea market)",
    address: "Rue des Rosiers, 93400 Saint-Ouen",
    lat: 48.9017,
    lng: 2.3427,
    notes: "The biggest antiques and flea market in the world. Open Saturday to Monday, so Saturday 31 Oct or Sunday 1 Nov fit your trip.",
    hours: "Saturday to Monday",
    closed: ["tue", "wed", "thu", "fri"],
    status: "want",
    tags: ["markets", "vintage"],
  },
  {
    id: "tang-freres",
    name: "Tang Frères",
    cat: "shop",
    area: "Chinatown",
    address: "48 Avenue d'Ivry, 75013 Paris",
    lat: 48.8257,
    lng: 2.3628,
    notes: "Huge Asian supermarket. Fun for snacks and sweets.",
    status: "want",
    tags: ["food & gifts"],
  },

  // ── Go ──
  {
    id: "galerie-dior",
    name: "La Galerie Dior",
    cat: "go",
    area: "Champs-Élysées",
    address: "11 Rue François 1er, 75008 Paris",
    lat: 48.867,
    lng: 2.3047,
    price: "€16 full price · €12 reduced (ages 10–26, students)",
    notes: "Dior exhibition. Booked for 30 Oct at 12:30.",
    hours: "11:00 – 19:00, last entry 17:30. Closed Tuesdays.",
    open: "11:00-19:00",
    closed: ["tue"],
    price: "€16 full price · €12 reduced (ages 10–26, students)",
    status: "want",
    tags: ["fashion", "museum", "rainy"],
  },
  {
    id: "louvre",
    name: "Louvre",
    cat: "go",
    area: "Louvre & Tuileries",
    address: "Rue de Rivoli, 75001 Paris",
    lat: 48.8611,
    lng: 2.3358,
    price: "€22 for EU visitors · €32 for non-EU visitors",
    notes: "To book. Date not chosen yet.",
    hours: "9:00 – 18:00, Wed and Fri until 21:00. Closed Tuesdays.",
    open: "09:00-18:00",
    openOn: {"wed": "09:00-21:00", "fri": "09:00-21:00"},
    closed: ["tue"],
    bookingUrl: "https://www.louvre.fr",
    bookAhead: "Book the 9:00 slot on Thursday 29 Oct. Popular slots sell out days ahead.",
    price: "€22 for EU visitors · €32 for non-EU visitors",
    status: "want",
    tags: ["museum", "landmark", "to book", "rainy"],
  },
  {
    id: "versailles",
    name: "Palace of Versailles",
    cat: "go",
    area: "Versailles (day trip)",
    address: "Place d'Armes, 78000 Versailles",
    lat: 48.8049,
    lng: 2.1204,
    price: "Free on Sunday 1 Nov (first Sunday of the month, reservation required) · otherwise Palace ticket €21",
    notes: "To book. Date not chosen yet. Plan for most of a day.",
    hours: "9:00 – 18:30 until 31 Oct, 9:00 – 17:30 from 1 Nov. Closed Mondays.",
    open: "09:00-17:30",
    closed: ["mon"],
    bookingUrl: "https://www.chateauversailles.fr",
    bookAhead: "Free on Sunday 1 Nov (first Sunday of the month), but a time slot must be reserved online. Morning slots go fast.",
    price: "Free on Sunday 1 Nov (first Sunday of the month, reservation required) · otherwise Palace ticket €21",
    status: "want",
    tags: ["landmark", "day trip", "to book"],
  },
  {
    id: "orsay",
    name: "Musée d'Orsay",
    cat: "go",
    area: "Saint-Germain",
    address: "Esplanade Valéry Giscard d'Estaing, 75007 Paris",
    lat: 48.86,
    lng: 2.3266,
    price: "€16 online · €14 on site · €12 on Thursday evenings · free for EU residents aged 18–25",
    notes: "Impressionists in a former railway station. Don't miss the giant clock window on the 5th floor, looking over the Seine to Sacré-Cœur.",
    bestTime: "Thursday evening is quieter",
    hours: "9:30 – 18:00, Thu until 21:45. Closed Mondays.",
    open: "09:30-18:00",
    openOn: {"thu": "09:30-21:45"},
    closed: ["mon"],
    bookingUrl: "https://www.musee-orsay.fr",
    bookAhead: "Buy tickets online (€16) to skip the ticket queue.",
    price: "€16 online · €14 on site · €12 on Thursday evenings · free for EU residents aged 18–25",
    status: "want",
    tags: ["museum", "view", "instagram", "rainy", "to book"],
  },
  {
    id: "eiffel-tower",
    name: "Eiffel Tower",
    cat: "go",
    area: "Eiffel Tower & Trocadéro",
    address: "Champ de Mars, 5 Avenue Anatole France, 75007 Paris",
    lat: 48.8584,
    lng: 2.2945,
    price: "See the official site",
    notes: "The view from the top is the classic one.",
    bestTime: "After dark it sparkles for 5 minutes every hour on the hour",
    hours: "9:30 – 23:45 every day",
    open: "09:30-23:45",
    bookingUrl: "https://www.toureiffel.paris",
    bookAhead: "Book summit tickets on the official site. They sell out.",
    price: "See the official site",
    status: "want",
    tags: ["landmark", "view", "to book"],
  },
  {
    id: "trocadero",
    name: "Trocadéro",
    cat: "go",
    area: "Eiffel Tower & Trocadéro",
    address: "Place du Trocadéro et du 11 Novembre, 75016 Paris",
    lat: 48.862,
    lng: 2.288,
    price: "Free",
    notes: "The best classic view and photo of the Eiffel Tower. Free.",
    bestTime: "Early morning for no crowds, or on the hour after dark for the sparkle",
    price: "Free",
    status: "want",
    tags: ["view", "instagram", "free", "landmark"],
  },
  {
    id: "bir-hakeim",
    name: "Pont de Bir-Hakeim",
    cat: "go",
    area: "Eiffel Tower & Trocadéro",
    address: "Pont de Bir-Hakeim, 75015 Paris",
    lat: 48.8556,
    lng: 2.2877,
    price: "Free",
    notes: "Two-level bridge with an iron colonnade and an Eiffel Tower view. A popular photo spot.",
    bestTime: "Morning light",
    price: "Free",
    status: "want",
    tags: ["instagram", "free", "view"],
  },
  {
    id: "invalides",
    name: "Les Invalides (Napoleon's tomb)",
    cat: "go",
    area: "Eiffel Tower & Trocadéro",
    address: "129 Rue de Grenelle, 75007 Paris",
    lat: 48.8565,
    lng: 2.3127,
    price: "€17",
    notes: "Golden dome with Napoleon's tomb and the army museum.",
    price: "€17",
    status: "want",
    tags: ["museum", "landmark", "rainy"],
  },
  {
    id: "sacre-coeur",
    name: "Sacré-Cœur",
    cat: "go",
    area: "Montmartre",
    address: "35 Rue du Chevalier de la Barre, 75018 Paris",
    lat: 48.8867,
    lng: 2.3431,
    price: "Free",
    notes: "White basilica on the hill with a panoramic view over Paris from the steps. Free entry.",
    bestTime: "Sunset from the steps",
    hours: "6:00 – 22:30 every day",
    open: "06:00-22:30",
    price: "Free",
    status: "want",
    tags: ["view", "church", "free", "landmark"],
  },
  {
    id: "place-du-tertre",
    name: "Place du Tertre",
    cat: "go",
    area: "Montmartre",
    address: "Place du Tertre, 75018 Paris",
    lat: 48.8865,
    lng: 2.3408,
    price: "Free",
    notes: "Square full of painters, 2 minutes from Sacré-Cœur. Walk on to Rue de l'Abreuvoir and La Maison Rose.",
    price: "Free",
    status: "want",
    tags: ["free"],
  },
  {
    id: "moulin-rouge",
    name: "Moulin Rouge",
    cat: "go",
    area: "Pigalle & Rue des Martyrs",
    address: "82 Boulevard de Clichy, 75018 Paris",
    lat: 48.8841,
    lng: 2.3322,
    price: "Free",
    notes: "The red windmill. Free to see from outside.",
    bestTime: "After dark, when it's lit up",
    price: "Free",
    status: "want",
    tags: ["instagram", "landmark", "free"],
  },
  {
    id: "notre-dame",
    name: "Notre-Dame",
    cat: "go",
    area: "Île de la Cité",
    address: "6 Parvis Notre-Dame, 75004 Paris",
    lat: 48.853,
    lng: 2.3499,
    price: "Free",
    notes: "Reopened after the restoration. Entry is free. Other sites selling tickets are not official.",
    hours: "Weekdays 7:50–19:00 (Thu until 22:00), weekends 8:15–19:30",
    open: "07:50-19:00",
    openOn: {"thu": "07:50-22:00", "sat": "08:15-19:30", "sun": "08:15-19:30"},
    bookingUrl: "https://www.notredamedeparis.fr",
    bookAhead: "Free. Reserve the Thursday 29 Oct evening slot from Tuesday 27 Oct (slots open 48 hours ahead). Only use notredamedeparis.fr.",
    price: "Free",
    status: "want",
    tags: ["church", "free", "landmark", "to book", "rainy"],
  },
  {
    id: "sainte-chapelle",
    name: "Sainte-Chapelle",
    cat: "go",
    area: "Île de la Cité",
    address: "10 Boulevard du Palais, 75001 Paris",
    lat: 48.8554,
    lng: 2.345,
    price: "€22",
    notes: "Chapel with floor-to-ceiling stained glass.",
    bestTime: "A sunny day, when the light comes through the glass",
    hours: "9:00 – 17:00 every day (October to March)",
    open: "09:00-17:00",
    bookingUrl: "https://www.sainte-chapelle.fr",
    bookAhead: "Book a time slot online.",
    price: "€22",
    status: "want",
    tags: ["church", "instagram", "to book", "rainy"],
  },
  {
    id: "arc-de-triomphe",
    name: "Arc de Triomphe",
    cat: "go",
    area: "Champs-Élysées",
    address: "Place Charles de Gaulle, 75008 Paris",
    lat: 48.8738,
    lng: 2.295,
    price: "€22",
    notes: "Climb to the rooftop for a view down the Champs-Élysées to the Eiffel Tower. Use the underground passage to cross.",
    bestTime: "Sunset",
    hours: "10:00 – 22:30 every day",
    open: "10:00-22:30",
    price: "€22",
    status: "want",
    tags: ["view", "landmark"],
  },
  {
    id: "champs-elysees",
    name: "Champs-Élysées",
    cat: "go",
    area: "Champs-Élysées",
    address: "Avenue des Champs-Élysées, 75008 Paris",
    lat: 48.8698,
    lng: 2.3076,
    price: "Free",
    notes: "Walk from the Arc de Triomphe down towards Place de la Concorde.",
    price: "Free",
    status: "want",
    tags: ["free", "landmark"],
  },
  {
    id: "musee-ysl",
    name: "Musée Yves Saint Laurent",
    cat: "go",
    area: "Champs-Élysées",
    address: "5 Avenue Marceau, 75116 Paris",
    lat: 48.865,
    lng: 2.2997,
    notes: "YSL's former couture house. A good match with the Dior gallery.",
    hours: "Closed Mondays",
    closed: ["mon"],
    status: "want",
    tags: ["fashion", "museum", "rainy"],
  },
  {
    id: "pont-alexandre-iii",
    name: "Pont Alexandre III",
    cat: "go",
    area: "Champs-Élysées",
    address: "Pont Alexandre III, 75008 Paris",
    lat: 48.8639,
    lng: 2.3136,
    price: "Free",
    notes: "The most ornate bridge in Paris, with gold statues and an Eiffel Tower view.",
    bestTime: "Sunset",
    price: "Free",
    status: "want",
    tags: ["instagram", "free", "view"],
  },
  {
    id: "palais-garnier",
    name: "Palais Garnier",
    cat: "go",
    area: "Opéra",
    address: "Place de l'Opéra, 75009 Paris",
    lat: 48.872,
    lng: 2.3316,
    notes: "The opera house. The grand staircase and foyer are open for visits.",
    hours: "Every day 10:00 – 17:00",
    hoursSource: "osm",
    openOn: {"mon": "10:00-17:00", "tue": "10:00-17:00", "wed": "10:00-17:00", "thu": "10:00-17:00", "fri": "10:00-17:00", "sat": "10:00-17:00", "sun": "10:00-17:00"},
    status: "want",
    tags: ["landmark", "instagram", "rainy"],
  },
  {
    id: "galeries-lafayette",
    name: "Galeries Lafayette",
    cat: "go",
    area: "Opéra",
    address: "40 Boulevard Haussmann, 75009 Paris",
    lat: 48.8738,
    lng: 2.332,
    price: "Free",
    notes: "See the stained-glass dome inside, then go up to the free rooftop terrace for the view.",
    bestTime: "Sunset on the rooftop",
    hours: "Mon–Sat 10:00 – 20:30 · Sun 11:00 – 20:00",
    hoursSource: "osm",
    openOn: {"mon": "10:00-20:30", "tue": "10:00-20:30", "wed": "10:00-20:30", "thu": "10:00-20:30", "fri": "10:00-20:30", "sat": "10:00-20:30", "sun": "11:00-20:00"},
    price: "Free",
    status: "want",
    tags: ["view", "free", "instagram", "rainy", "department store"],
  },
  {
    id: "orangerie",
    name: "Musée de l'Orangerie",
    cat: "go",
    area: "Louvre & Tuileries",
    address: "Jardin des Tuileries, 75001 Paris",
    lat: 48.8638,
    lng: 2.3227,
    price: "€11",
    notes: "Monet's Water Lilies in two oval rooms. Small, about 1 hour.",
    hours: "9:00 – 18:00. Closed Tuesdays.",
    open: "09:00-18:00",
    closed: ["tue"],
    price: "€11",
    status: "want",
    tags: ["museum", "rainy"],
  },
  {
    id: "tuileries",
    name: "Jardin des Tuileries",
    cat: "go",
    area: "Louvre & Tuileries",
    address: "Place de la Concorde to the Louvre, 75001 Paris",
    lat: 48.8635,
    lng: 2.3275,
    price: "Free",
    notes: "Garden between the Louvre and Place de la Concorde. Good walk between museums.",
    hours: "Every day 07:30 – 21:00",
    hoursSource: "osm",
    openOn: {"mon": "07:30-21:00", "tue": "07:30-21:00", "wed": "07:30-21:00", "thu": "07:30-21:00", "fri": "07:30-21:00", "sat": "07:30-21:00", "sun": "07:30-21:00"},
    price: "Free",
    status: "want",
    tags: ["garden", "free"],
  },
  {
    id: "palais-royal",
    name: "Palais-Royal gardens",
    cat: "go",
    area: "Louvre & Tuileries",
    address: "8 Rue de Montpensier, 75001 Paris",
    lat: 48.8638,
    lng: 2.337,
    price: "Free",
    notes: "Quiet garden with the black-and-white striped columns, a popular photo spot. Café Kitsuné is here.",
    price: "Free",
    status: "want",
    tags: ["garden", "instagram", "free"],
  },
  {
    id: "galerie-vivienne",
    name: "Galerie Vivienne",
    cat: "go",
    area: "Louvre & Tuileries",
    address: "4 Rue des Petits Champs, 75002 Paris",
    lat: 48.8665,
    lng: 2.3398,
    price: "Free",
    notes: "The prettiest covered passage, with a mosaic floor and glass roof.",
    hours: "Mon–Sat 08:30 – 20:30",
    hoursSource: "osm",
    openOn: {"mon": "08:30-20:30", "tue": "08:30-20:30", "wed": "08:30-20:30", "thu": "08:30-20:30", "fri": "08:30-20:30", "sat": "08:30-20:30"},
    price: "Free",
    status: "want",
    tags: ["instagram", "rainy", "free"],
  },
  {
    id: "passage-panoramas",
    name: "Passage des Panoramas",
    cat: "go",
    area: "Grands Boulevards",
    address: "11 Boulevard Montmartre, 75002 Paris",
    lat: 48.8711,
    lng: 2.3418,
    price: "Free",
    notes: "The oldest covered passage in Paris (1799). Small restaurants and old stamp shops.",
    hours: "Every day 06:00 – midnight",
    hoursSource: "osm",
    openOn: {"mon": "06:00-24:00", "tue": "06:00-24:00", "wed": "06:00-24:00", "thu": "06:00-24:00", "fri": "06:00-24:00", "sat": "06:00-24:00", "sun": "06:00-24:00"},
    price: "Free",
    status: "want",
    tags: ["rainy", "free"],
  },
  {
    id: "place-des-vosges",
    name: "Place des Vosges",
    cat: "go",
    area: "Le Marais",
    address: "Place des Vosges, 75004 Paris",
    lat: 48.8556,
    lng: 2.3655,
    price: "Free",
    notes: "The oldest planned square in Paris, with red-brick arcades. Start a Marais walk here.",
    price: "Free",
    status: "want",
    tags: ["free"],
  },
  {
    id: "luxembourg",
    name: "Jardin du Luxembourg",
    cat: "go",
    area: "Saint-Germain",
    address: "Rue de Médicis, 75006 Paris",
    lat: 48.8462,
    lng: 2.3372,
    price: "Free",
    notes: "Palace gardens with the pond and green chairs.",
    price: "Free",
    status: "want",
    tags: ["garden", "free"],
  },
  {
    id: "rue-cremieux",
    name: "Rue Crémieux",
    cat: "go",
    area: "Bastille & Gare de Lyon",
    address: "Rue Crémieux, 75012 Paris",
    lat: 48.8471,
    lng: 2.3708,
    price: "Free",
    notes: "Pedestrian street of pastel houses. People live here, so keep it quiet.",
    bestTime: "Morning, when it's quiet",
    price: "Free",
    status: "want",
    tags: ["instagram", "free"],
  },
  {
    id: "chinatown",
    name: "Chinatown",
    cat: "go",
    area: "Chinatown",
    address: "Avenue de Choisy, 75013 Paris",
    lat: 48.827,
    lng: 2.36,
    price: "Free",
    notes: "Europe's largest Chinatown, between Avenue de Choisy and Avenue d'Ivry. Pho, dim sum, bubble tea and the Tang Frères supermarket.",
    price: "Free",
    status: "want",
    tags: ["neighbourhood", "free"],
  },
  {
    id: "little-tokyo",
    name: "Little Tokyo (Rue Sainte-Anne)",
    cat: "go",
    area: "Little Tokyo",
    address: "Rue Sainte-Anne, 75001 Paris",
    lat: 48.8665,
    lng: 2.3355,
    notes: "The Japanese quarter: ramen, udon, Japanese bakeries and grocery shops, with Korean spots on the side streets.",
    status: "want",
    tags: ["neighbourhood"],
  },
  {
    id: "belleville",
    name: "Belleville",
    cat: "go",
    area: "Belleville",
    address: "Rue de Belleville, 75020 Paris",
    lat: 48.8722,
    lng: 2.381,
    price: "Free",
    notes: "Paris's second Chinatown, with street art on Rue Dénoyez and the Parc de Belleville view.",
    price: "Free",
    status: "want",
    tags: ["neighbourhood", "free"],
  },
  {
    id: "little-india",
    name: "Little India (Passage Brady)",
    cat: "go",
    area: "Grands Boulevards",
    address: "46 Rue du Faubourg Saint-Denis, 75010 Paris",
    lat: 48.8722,
    lng: 2.3535,
    notes: "Covered passage full of Indian restaurants.",
    status: "want",
    tags: ["neighbourhood"],
  },
  {
    id: "parc-de-belleville",
    name: "Parc de Belleville",
    cat: "go",
    area: "Belleville",
    address: "47 Rue des Couronnes, 75020 Paris",
    lat: 48.871,
    lng: 2.3848,
    price: "Free",
    notes: "Hillside park with one of the best free views over Paris to the Eiffel Tower.",
    bestTime: "Sunset",
    hours: "Mon–Fri 08:00 – 19:00 · Sat–Sun 09:00 – 19:00",
    hoursSource: "osm",
    openOn: {"mon": "08:00-19:00", "tue": "08:00-19:00", "wed": "08:00-19:00", "thu": "08:00-19:00", "fri": "08:00-19:00", "sat": "09:00-19:00", "sun": "09:00-19:00"},
    price: "Free",
    status: "want",
    tags: ["view", "free", "garden"],
  },

  // ── Do ──
  {
    id: "seine-cruise",
    name: "Seine river cruise",
    cat: "do",
    area: "Eiffel Tower & Trocadéro",
    address: "Port de la Bourdonnais, 75007 Paris",
    lat: 48.8597,
    lng: 2.293,
    price: "From €17",
    notes: "About 1 hour on the river past the main sights.",
    bestTime: "Evening, when the Eiffel Tower is lit",
    price: "From €17",
    status: "want",
    tags: ["boat", "evening", "view"],
  },
  {
    id: "marais-walk",
    name: "Walk around Le Marais",
    cat: "do",
    area: "Le Marais",
    address: "Place des Vosges, 75004 Paris",
    lat: 48.8556,
    lng: 2.3655,
    price: "Free",
    notes: "Small streets, boutiques and cafés. Go from Place des Vosges to Rue des Rosiers and Rue de Bretagne.",
    price: "Free",
    status: "want",
    tags: ["walk", "free"],
  },
  {
    id: "montmartre-walk",
    name: "Walk around Montmartre",
    cat: "do",
    area: "Montmartre",
    address: "Place des Abbesses, 75018 Paris",
    lat: 48.8844,
    lng: 2.3385,
    price: "Free",
    notes: "Go from Abbesses up to Sacré-Cœur, Place du Tertre, Rue de l'Abreuvoir and La Maison Rose. Take the funicular if you're tired.",
    price: "Free",
    status: "want",
    tags: ["walk", "free", "instagram"],
  },
  {
    id: "canal-walk",
    name: "Walk along Canal Saint-Martin",
    cat: "do",
    area: "Canal Saint-Martin",
    address: "Quai de Valmy, 75010 Paris",
    lat: 48.871,
    lng: 2.364,
    price: "Free",
    notes: "Iron footbridges, locks and cafés along the water. Combine with Du Pain et des Idées.",
    price: "Free",
    status: "want",
    tags: ["walk", "free", "instagram"],
  },
  {
    id: "street-art-denoyez",
    name: "Street art on Rue Dénoyez",
    cat: "do",
    area: "Belleville",
    address: "Rue Dénoyez, 75020 Paris",
    lat: 48.871,
    lng: 2.379,
    price: "Free",
    notes: "A short street covered in ever-changing graffiti.",
    price: "Free",
    status: "want",
    tags: ["free", "instagram"],
  },
  {
    id: "moulin-rouge-show",
    name: "Moulin Rouge show",
    cat: "do",
    area: "Pigalle & Rue des Martyrs",
    address: "82 Boulevard de Clichy, 75018 Paris",
    lat: 48.8841,
    lng: 2.3322,
    notes: "The classic cabaret show.",
    bookingUrl: "https://www.moulinrouge.fr",
    bookAhead: "Book online well ahead. Evening shows sell out.",
    status: "maybe",
    tags: ["evening", "to book"],
  },
];

// Planned and booked things, shown in the calendar.
const EVENTS = [
  {
    id: "plan-trocadero",
    date: "2026-10-28",
    start: "17:00",
    title: "Eiffel Tower view at Trocadéro",
    placeId: "trocadero",
    booked: false,
    notes: "Sunset is at 17:38. The classic photo spot for the Eiffel Tower.",
  },
  {
    id: "plan-les-ombres",
    date: "2026-10-28",
    start: "19:00",
    title: "Drinks with an Eiffel Tower view",
    placeId: "les-ombres",
    booked: false,
    notes: "Rooftop bar on the Musée du quai Branly, facing the tower, 10 minutes' walk from Trocadéro. The tower sparkles for 5 minutes at 20:00, 21:00 and 22:00. Book a table for dinner.",
  },
  {
    id: "plan-louvre",
    date: "2026-10-29",
    start: "09:00",
    end: "12:30",
    title: "Louvre",
    placeId: "louvre",
    booked: false,
    notes: "Book the 9:00 time slot on louvre.fr. Mornings right at opening are the calmest.",
  },
  {
    id: "plan-orsay",
    date: "2026-10-29",
    start: "14:00",
    end: "17:30",
    title: "Musée d'Orsay",
    placeId: "orsay",
    booked: false,
    notes: "10 minutes' walk from the Louvre across the Pont Royal. Open until 21:45 on Thursdays, so there's no rush. Tickets are €16 online.",
  },
  {
    id: "plan-notre-dame",
    date: "2026-10-29",
    start: "19:00",
    title: "Notre-Dame",
    placeId: "notre-dame",
    booked: false,
    notes: "25 minutes' walk along the Seine from Orsay. Open until 22:00 on Thursdays, and evenings after 19:00 are the quietest. Reserve the free time slot on notredamedeparis.fr from Tuesday 27 Oct (slots open 48 hours ahead).",
  },
  {
    id: "plan-walk-luxembourg",
    date: "2026-10-30",
    start: "14:00",
    title: "Walk to the Luxembourg Garden",
    placeId: "luxembourg",
    booked: false,
    notes: "About 50 minutes on foot from the Dior gallery: cross Pont Alexandre III, pass Les Invalides, then go through Saint-Germain (Café de Flore and Pierre Hermé are on the way). The garden closes around 17:00 at this time of year.",
  },
  {
    id: "plan-versailles",
    date: "2026-11-01",
    start: "09:00",
    end: "17:30",
    title: "Versailles, whole day",
    placeId: "versailles",
    booked: false,
    notes: "Free entry: it's the first Sunday of the month, but you must reserve a time slot on chateauversailles.fr. Morning slots go fast. Take the RER C to Versailles Château Rive Gauche (about 40 minutes, one regular ticket each way). The palace closes at 17:30.",
  },
  {
    id: "train-to-paris",
    date: "2026-10-28",
    start: "08:10",
    end: "11:43",
    title: "Eurostar to Paris",
    where: "Paris Gare du Nord",
    address: "18 Rue de Dunkerque, 75010 Paris",
    booked: true,
    details: [
      ["From", "Amsterdam Centraal 08:10"],
      ["To", "Paris Gare du Nord 11:43"],
      ["Class", "Eurostar Standard · direct, 3 h 33 min"],
      ["Coach", "17"],
      ["Seats", "31 and 32"],
    ],
    notes: "",
  },
  {
    id: "train-home",
    date: "2026-11-02",
    start: "18:15",
    end: "21:50",
    title: "Eurostar home",
    where: "Paris Gare du Nord",
    address: "18 Rue de Dunkerque, 75010 Paris",
    booked: true,
    details: [
      ["From", "Paris Gare du Nord 18:15"],
      ["To", "Amsterdam Centraal 21:50"],
      ["Class", "Eurostar Standard · direct, 3 h 35 min"],
      ["Coach", "16"],
      ["Seats", "31 and 32"],
    ],
    notes: "Gare du Nord is busy at rush hour. Leave enough time to get there with your bags.",
  },
  {
    id: "dior-exhibition",
    date: "2026-10-30",
    start: "12:30",
    title: "Dior exhibition",
    placeId: "galerie-dior",
    booked: true,
    confirmation: "",
    notes: "3 tickets. Open them under Plan → Our tickets on your phone. Entry is guaranteed within 30 minutes of your time slot. No large bags or suitcases allowed inside.",
  },
];

// Notes shown on each day in the Plan tab.
const DAY_NOTES = {
  "2026-10-28": "Arrival day: train arrives at Gare du Nord at 11:43. Idea for lunch: Bouillon Chartier Gare de l'Est is a short walk from the station. Evening: Eiffel Tower views.",
  "2026-10-29": "Museum day: Louvre, Musée d'Orsay, then Notre-Dame in the evening. Idea for lunch between the two museums: Little Tokyo (ramen and udon) is 10 minutes from the Louvre.",
  "2026-10-30": "Dior at 12:30 (entry within 30 minutes of the slot, no big bags), then a long walk to the Luxembourg Garden.",
  "2026-10-31": "Free day, nothing planned yet. Saturday is the busiest day at museums and shops. L'As du Fallafel is closed. The Saint-Ouen flea market is open.",
  "2026-11-01": "Versailles day. Sunday and a public holiday (All Saints' Day), so many shops in Paris are closed.",
  "2026-11-02": "Departure day: train leaves Gare du Nord at 18:15. Ask the hotel to keep your bags after check-out. Musée d'Orsay, Versailles, Musée Yves Saint Laurent and the Marché des Enfants Rouges are closed on Mondays."
};

// Info tab.
const INFO = {
  "sections": [
    {
      "id": "getting",
      "title": "Getting around",
      "c": "do",
      "items": [
        {
          "t": "Metro, RER and train ticket: €2.55",
          "d": "One ticket per journey anywhere in the Paris region (2026 price). Bus and tram tickets are €2.05. Paper tickets are gone: load tickets onto a Navigo Easy card (€2 at station counters and machines) or onto your phone in the Île-de-France Mobilités app."
        },
        {
          "t": "You can't tap a bank card at metro gates yet",
          "d": "Contactless bank cards only work on buses and a few lines for now. Buy a ticket first."
        },
        {
          "t": "Arriving at Gare du Nord",
          "d": "Your Eurostar arrives at Gare du Nord. From there, metro lines 4 and 5 and the RER B, D and E go across the city. The official taxi rank is outside the station; ignore anyone offering a ride inside."
        },
        {
          "t": "Taxis from the station",
          "d": "Taxis from Gare du Nord run on the meter (the fixed fares are only for the airports). Uber, Bolt and G7 also pick up here."
        },
        {
          "t": "Uber, Bolt and G7",
          "d": "All work in Paris. G7 is the main official taxi company and has its own app."
        },
        {
          "t": "Walking",
          "d": "Central Paris is compact. Most places in this app are 15–30 minutes apart on foot, and walking is often faster than the metro for short trips."
        },
        {
          "t": "Montmartre funicular",
          "d": "Takes you up the hill to Sacré-Cœur on a normal metro ticket."
        }
      ]
    },
    {
      "id": "know",
      "title": "Good to know",
      "c": "cafe",
      "items": [
        {
          "t": "Always say “Bonjour”",
          "d": "When you walk into a shop, café or bakery, say bonjour first. It makes a big difference to how you're treated."
        },
        {
          "t": "Tipping",
          "d": "Service is already included in the price. Round up or leave €1–2 for coffee, and 5–10% for great service at dinner if you like."
        },
        {
          "t": "Tap water is free",
          "d": "Ask for “une carafe d'eau” instead of bottled water."
        },
        {
          "t": "Coffee costs more at a table",
          "d": "Standing at the bar is cheaper than sitting at a table or on the terrace."
        },
        {
          "t": "Meal times",
          "d": "Lunch is 12:00–14:30 and dinner usually starts 19:30. Many restaurants close between lunch and dinner, but brasseries and bouillons serve all day."
        },
        {
          "t": "Museum closing days",
          "d": "The Louvre, Orangerie and Dior gallery close on Tuesdays. Musée d'Orsay, Versailles and Musée Yves Saint Laurent close on Mondays."
        },
        {
          "t": "Sunday 1 November is a public holiday",
          "d": "All Saints' Day. Many shops and some bakeries are closed. Most museums and sights stay open."
        },
        {
          "t": "Winter time",
          "d": "France changes to winter time on 25 October, before you arrive. Sunset is around 17:30, so plan views and photos for about 17:00."
        },
        {
          "t": "Plugs",
          "d": "Type E sockets, 230 V."
        },
        {
          "t": "What to drink",
          "d": "Café crème is coffee with milk, “un café” is an espresso. Try a kir (white wine with blackcurrant liqueur) or kir royal (with champagne) as an apéritif."
        }
      ]
    },
    {
      "id": "avoid",
      "title": "Tourist traps to avoid",
      "c": "drink",
      "items": [
        {
          "t": "Friendship-bracelet sellers",
          "d": "Mostly at the bottom of the Sacré-Cœur steps. They tie a bracelet on your wrist, then demand money. Keep your hands in your pockets and keep walking."
        },
        {
          "t": "Petition clipboards",
          "d": "People asking you to sign a petition near the Eiffel Tower and Louvre. It's a distraction for pickpocketing. Say no and walk on."
        },
        {
          "t": "The “found a gold ring” trick",
          "d": "Someone ‘finds’ a ring next to you and offers to sell it. It's fake."
        },
        {
          "t": "Shell games on bridges",
          "d": "The players in the crowd are part of the team. You can't win."
        },
        {
          "t": "Pickpockets",
          "d": "Most common on metro lines 1 and 4, the RER B, at Gare du Nord and around the Eiffel Tower. Don't leave your phone on a café table by the street."
        },
        {
          "t": "Unofficial taxis",
          "d": "Ignore anyone offering a ride inside the airport. Use the official taxi rank or an app."
        },
        {
          "t": "Restaurants right next to top sights",
          "d": "Places with picture menus and people inviting you in are usually poor value. Walk two streets away."
        },
        {
          "t": "Fake Notre-Dame tickets",
          "d": "Entry is free. Only reserve on notredamedeparis.fr."
        },
        {
          "t": "Currency exchange counters",
          "d": "Rates at airports and tourist areas are bad. Pay by card, and if a card machine asks, choose to pay in euros."
        }
      ]
    }
  ],
  "phrases": [
    {
      "fr": "Bonjour / Bonsoir",
      "say": "bohn-zhoor / bohn-swahr",
      "en": "Hello / Good evening. Say it when you walk in anywhere."
    },
    {
      "fr": "Merci (beaucoup)",
      "say": "mehr-see (boh-koo)",
      "en": "Thank you (very much)"
    },
    {
      "fr": "S'il vous plaît",
      "say": "seel voo pleh",
      "en": "Please"
    },
    {
      "fr": "Pardon / Excusez-moi",
      "say": "par-dohn / ex-kew-zay mwah",
      "en": "Sorry / Excuse me"
    },
    {
      "fr": "Parlez-vous anglais ?",
      "say": "par-lay voo ahn-gleh",
      "en": "Do you speak English?"
    },
    {
      "fr": "Une table pour deux, s'il vous plaît",
      "say": "ewn tah-bluh poor duh",
      "en": "A table for two, please"
    },
    {
      "fr": "Je voudrais…",
      "say": "zhuh voo-dreh",
      "en": "I would like…"
    },
    {
      "fr": "Deux croissants, s'il vous plaît",
      "say": "duh krwah-sahn",
      "en": "Two croissants, please"
    },
    {
      "fr": "Une boîte de macarons",
      "say": "ewn bwaht duh ma-ka-rohn",
      "en": "A box of macarons"
    },
    {
      "fr": "Un café / Un café crème",
      "say": "uhn ka-fay / ka-fay krem",
      "en": "An espresso / A coffee with milk"
    },
    {
      "fr": "Un chocolat chaud",
      "say": "uhn sho-ko-la shoh",
      "en": "A hot chocolate"
    },
    {
      "fr": "Une carafe d'eau",
      "say": "ewn ka-raf doh",
      "en": "A jug of tap water (free)"
    },
    {
      "fr": "Sur place / À emporter",
      "say": "sewr plahs / ah ahm-por-tay",
      "en": "To eat in / To take away"
    },
    {
      "fr": "L'addition, s'il vous plaît",
      "say": "la-dee-syohn",
      "en": "The bill, please"
    },
    {
      "fr": "C'est combien ?",
      "say": "say kohm-byan",
      "en": "How much is it?"
    },
    {
      "fr": "Où sont les toilettes ?",
      "say": "oo sohn lay twa-let",
      "en": "Where are the toilets?"
    },
    {
      "fr": "Je suis allergique à…",
      "say": "zhuh swee a-lehr-zheek ah",
      "en": "I'm allergic to…"
    },
    {
      "fr": "Au revoir, bonne journée",
      "say": "oh ruh-vwahr, bun zhoor-nay",
      "en": "Goodbye, have a good day"
    }
  ],
  "emergency": [
    {
      "num": "112",
      "t": "All emergencies",
      "d": "Works from any phone. English spoken."
    },
    {
      "num": "15",
      "t": "Medical emergency (SAMU)",
      "d": ""
    },
    {
      "num": "17",
      "t": "Police",
      "d": ""
    },
    {
      "num": "18",
      "t": "Fire brigade",
      "d": ""
    },
    {
      "num": "114",
      "t": "Emergency by text message",
      "d": "If you can't speak on the phone."
    }
  ]
};
